
(function(c){function d(b,a){return parseInt(c.curCSS(b.jquery?b[0]:b,a,true))||0}c.dimensions={version:"1.2"};c.each(["Height","Width"],function(b,a){c.fn["inner"+a]=function(){if(this[0]){var b=a=="Height"?"Top":"Left",c=a=="Height"?"Bottom":"Right";return this.is(":visible")?this[0]["client"+a]:d(this,a.toLowerCase())+d(this,"padding"+b)+d(this,"padding"+c)}};c.fn["outer"+a]=function(b){if(this[0]){var e=a=="Height"?"Top":"Left",f=a=="Height"?"Bottom":"Right",b=c.extend({margin:false},b||{});return(this.is(":visible")?this[0]["offset"+a]:d(this,a.toLowerCase())+d(this,"border"+e+"Width")+d(this,"border"+f+"Width")+d(this,"padding"+e)+d(this,"padding"+f))+(b.margin?d(this,"margin"+e)+d(this,"margin"+f):0)}}});c.each(["Left","Top"],function(b,a){c.fn["scroll"+a]=function(b){return!this[0]?void 0:b!=void 0?this.each(function(){this==window||this==document?window.scrollTo(a=="Left"?b:c(window).scrollLeft(),a=="Top"?b:c(window).scrollTop()):this["scroll"+a]=b}):this[0]==window||this[0]==document?self[a=="Left"?"pageXOffset":"pageYOffset"]||c.boxModel&&document.documentElement["scroll"+a]||document.body["scroll"+a]:this[0]["scroll"+a]}});c.fn.extend({position:function(){var b=this[0],a,c,e;if(b){e=this.offsetParent();if(!e.length)return a;a=this.offset();c=e.offset();a.top-=d(b,"marginTop");a.left-=d(b,"marginLeft");c.top+=d(e,"borderTopWidth");c.left+=d(e,"borderLeftWidth");a={top:a.top-c.top,left:a.left-c.left}}return a},offsetParent:function(){if(this.css("display")==null)return false;for(var b=this[0].offsetParent;b&&!/^body|html$/i.test(b.tagName)&&c.css(b,"position")=="static";)b=b.offsetParent;return c(b)}})})(jQuery);(function($){$.fn.inputHintBox=function(options){options=$.extend({},$.inputHintBoxer.defaults,options);this.each(function(){new $.inputHintBoxer(this,options);});return this;}
$.inputHintBoxer=function(input,options){var $guideObject=$(options.el||input),$input=$(input),box,boxMouseDown=false,html='';if(($guideObject.attr('type')=='radio'||$guideObject.attr('type')=='checkbox')&&$guideObject.parent().is('label')){$guideObject=$($guideObject.parent());}
function init(){var boxHtml=options.html!=''?options.html:options.source=='attr'?$input.attr(options.attr):'';if(typeof boxHtml==="undefined")boxHtml='';box=options.div!=''?options.div:$("<div/>").addClass(options.className);box=box.css('display','none').addClass('_hintBox').appendTo(options.attachTo);$input.data("tooltip",boxHtml);$input.focus(function(){$('body').mousedown(global_mousedown_listener)
$(window).unbind("scroll",srollListener).scroll(srollListener);box.data("tooltip",$input.data("tooltip"));show();}).blur(function(){prepare_hide();}).bind('mouseover',function(e){$('body').mousedown(global_mousedown_listener);$(window).unbind("scroll",srollListener).scroll(srollListener);box.data("tooltip",$input.data("tooltip"));if(Runner.Event.prototype.getTarget(e.originalEvent).nodeName!="OPTION"){show();}}).bind('mouseout',function(e){prepare_hide();});}
function srollListener(){$.inputHintBoxer.hide(true);}
function align(){var viewContainer=Runner.getAbsoluteParent($guideObject[0]),that=this;if(options.isFly){box.css('z-index',Runner.genZIndexMax());}
box.css({position:"absolute"});Runner.setLeftTop($guideObject[0],box.get(0),viewContainer,true);}
function show(){clearTimeout($.inputHintBoxer.mostRecentHideTimer);clearTimeout(this.timeout);this.timeout=setTimeout(function(){$('div.shiny_box').hide();align();if(options.div_sub=='')box.html("tooltip",box.data("tooltip"));else $(options.div_sub,box).html(box.data("tooltip"));box.show();},100);}
function prepare_hide(noTimeout){$('body').click(global_click_listener);if(boxMouseDown)return;if(noTimeout){$.inputHintBoxer.hide(true);}else{$.inputHintBoxer.mostRecentHideTimer=setTimeout(function(){$.inputHintBoxer.hide()},300);}}
var global_click_listener=function(e){var $e=$(e.target),c='._hintBox';clearTimeout($.inputHintBoxer.mostRecentHideTimer);if($e.parents(c).length==0&&$e.is(c)==false)$.inputHintBoxer.hide();};var global_mousedown_listener=function(e){var $e=$(e.target),c='._hintBox';boxMouseDown=($e.parents(c).length!=0||$e.is(c)!=false);}
$.inputHintBoxer.hide=function(noTimeout){clearTimeout($.inputHintBoxer.mostRecentHideTimer);clearTimeout(this.timeout);this.timeout=setTimeout(function(){$('body').unbind('click',global_click_listener);$('body').unbind('mousedown',global_mousedown_listener);if(noTimeout){box.hide();}else{box.fadeOut('fast');}},200);}
init();return{}};$.inputHintBoxer.mostRecentHideTimer=0;$.inputHintBoxer.defaults={div:'',className:'input_hint_box',source:'attr',div_sub:'',attr:'title',html:'',incrementLeft:5,incrementTop:0,attachTo:'body'}})(jQuery);