-- +---------------------------------------------------------
-- | MODEL       : LC-PostGres
-- | AUTHOR      :
-- | GENERATED BY: Open System Architect
-- +---------------------------------------------------------
-- | WARNING     : Review before execution
-- +---------------------------------------------------------

ALTER DATABASE LC SET timezone to 'UTC';

-- +---------------------------------------------------------
-- | CREATE
-- +---------------------------------------------------------
CREATE TABLE alert_communication_config
(
  tenant_id integer NOT NULL,
  phase integer NOT NULL,
  elapsed_time integer NOT NULL,
  CONSTRAINT alert_comm_config_pk PRIMARY KEY (tenant_id , phase )
);
CREATE TABLE alert_communication
(
  tenant_id integer NOT NULL,
  phase_indicator integer,
  phase_starttime timestamp without time zone,
  phase_endtime timestamp without time zone,
  success_indicator boolean,
  cycle_starttime timestamp without time zone,
  CONSTRAINT alert_comm_pk PRIMARY KEY (tenant_id )
);
CREATE TABLE light_filter_type
(
  light_filter_type_id serial NOT NULL,
  name character varying(4094) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  PRIMARY KEY (light_filter_type_id)
);
CREATE TABLE light_filter_value
(
  light_filter_value_id serial NOT NULL,
  filter_value character varying(4094) NOT NULL,
  light_filter_type_id integer NOT NULL,
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  PRIMARY KEY (light_filter_value_id),
  CONSTRAINT fk_light_filter_type FOREIGN KEY (light_filter_type_id)
      REFERENCES light_filter_type (light_filter_type_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
);
CREATE TABLE day_of_week
(
  day_of_week_id integer NOT NULL,
  name character varying(10) NOT NULL,
  create_date timestamp with time zone,
  create_user character varying(20),
  PRIMARY KEY  (day_of_week_id)
);
CREATE TABLE lc_action
(
  lc_action_id integer NOT NULL,
  description character varying(200) NOT NULL,
  create_date timestamp with time zone,
  create_user character varying(20),
  PRIMARY KEY (lc_action_id)
);
CREATE TABLE failure
(
  failure_id serial NOT NULL,
  label_key character varying(80) NOT NULL,
  create_date timestamp with time zone,
  create_user character varying(20),
  lc_action_id integer,
  PRIMARY KEY (failure_id)
);
CREATE INDEX nx_failure_lc_action_lc_action_id ON failure
(
  lc_action_id
);

CREATE TABLE tenant
(
  tenant_id serial NOT NULL,
  name character varying(20) NOT NULL,
  description character varying(80),
  rni_code character varying(5) NOT NULL,
  server_name character varying(150) NOT NULL,
  gateway_rni_location character varying(150),
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone,
  latitude float8,
  longitude float8,
  min_smartpoint_comm_time integer NOT NULL,
  light_time_zone character varying(80),
  ecomode_disable boolean DEFAULT false,
  batch_process_time integer NOT NULL,
  communication_cycle_timeout integer,
  number_api_access_hour integer DEFAULT 10,
  PRIMARY KEY (tenant_id)
);
CREATE UNIQUE INDEX ux_tenant_rni_code ON tenant
(
  rni_code
);

CREATE UNIQUE INDEX ux_tenant_server_name ON tenant
(
  server_name
);

CREATE TABLE api_control (
                tenant_id INTEGER NOT NULL,
                count INTEGER NOT NULL,
                first_date TIMESTAMP,
                CONSTRAINT tenant_id PRIMARY KEY (tenant_id)
);

CREATE TABLE grouping
(
  grouping_id serial NOT NULL,
  name character varying(100) NOT NULL,
  description character varying(150),
  create_date timestamp with time zone DEFAULT (NULL) NOT NULL,
  modified_date timestamp with time zone,
  create_user character varying(20) NOT NULL,
  modify_user character varying(20),
  tenant_id integer NOT NULL,
  latitude float8,
  longitude float8,
  PRIMARY KEY (grouping_id)
);
CREATE UNIQUE INDEX ux_grouping_tenant_id_name ON grouping
(
  tenant_id,
  upper(name::text) COLLATE pg_catalog."default"
);

CREATE INDEX nx_grouping_tenant_id ON grouping
(
  tenant_id
);

CREATE TABLE tag
(
  tag_id serial NOT NULL,
  name character varying(100),
  create_date timestamp with time zone,
  modified_date timestamp with time zone,
  create_user character varying(20) NOT NULL,
  modify_user character varying(20),
  tenant_id integer,
  auto_group boolean DEFAULT false,
  address_related boolean DEFAULT false,
  PRIMARY KEY (tag_id)
);
CREATE INDEX nx_tag_tenant_id ON tag
(
  tenant_id
);

CREATE UNIQUE INDEX ux_tag_tenant_id_name
  ON tag
  USING btree
  (tenant_id , upper(name::text) COLLATE pg_catalog."default" );

CREATE TABLE light_schedule (
                light_id INTEGER NOT NULL,
                sunrise_time CHARACTER VARYING(20),
                sunrise_offset INTEGER,
                sunset_time CHARACTER VARYING(20),
                sunset_offset INTEGER,
                create_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                modified_date TIMESTAMP WITH TIME ZONE,
                create_user CHARACTER VARYING(20) NOT NULL,
                modified_user CHARACTER VARYING(20),
                CONSTRAINT pk_light_schedule PRIMARY KEY (light_id)
);

CREATE TABLE light_last_operational_data (
                light_id INTEGER NOT NULL,
                ac_voltage DOUBLE PRECISION,
                ac_voltage_min DOUBLE PRECISION,
                ac_voltage_min_date TIMESTAMP WITH TIME ZONE,
                ac_voltage_max DOUBLE PRECISION,
                ac_voltage_max_date TIMESTAMP WITH TIME ZONE,
                ac_current DOUBLE PRECISION,
                ac_current_min DOUBLE PRECISION,
                ac_current_min_date TIMESTAMP WITH TIME ZONE,
                ac_current_max DOUBLE PRECISION,
                ac_current_max_date TIMESTAMP WITH TIME ZONE,
                consumption DOUBLE PRECISION,
                consumption_min DOUBLE PRECISION,
                consumption_max DOUBLE PRECISION,
                create_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                modified_date TIMESTAMP WITH TIME ZONE,
                create_user CHARACTER VARYING(20) NOT NULL,
                modified_user CHARACTER VARYING(20),
                CONSTRAINT pk_light_last_op_data PRIMARY KEY (light_id)
);

CREATE TABLE light_configuration (
                light_id INTEGER NOT NULL,
                housing CHARACTER VARYING(30),
                housing_color CHARACTER VARYING(20),
                dimmable BOOLEAN DEFAULT FALSE,
                lamp_type_wattage_dimmable CHARACTER VARYING(20),
                wattage_rating CHARACTER VARYING(10),
                input_voltage_range CHARACTER VARYING(20),
                color_temperature CHARACTER VARYING(10),
                manufacturer CHARACTER VARYING(30),
                firmware_version CHARACTER VARYING(10),
                model_number CHARACTER VARYING(30),
                lower_assembly_serial_number CHARACTER VARYING(20),
                upper_assembly_serial_number CHARACTER VARYING(20),
                frequency CHARACTER VARYING(10),
                date_added TIMESTAMP WITH TIME ZONE,
                bulb_serial_number CHARACTER VARYING(20),
                ballast_serial_number CHARACTER VARYING(20),
                customer_serial_number CHARACTER VARYING(20),
                create_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                modified_date TIMESTAMP WITH TIME ZONE,
                create_user CHARACTER VARYING(20) NOT NULL,
                modified_user CHARACTER VARYING(20),
                CONSTRAINT pk_light_configuration_id PRIMARY KEY (light_id)
);


CREATE TABLE light
(
  -- Device columns
  light_id serial NOT NULL,
  light_type smallint NOT NULL,
  lifecycle_state smallint NOT NULL,
  light_state smallint NOT NULL,

  create_date timestamp with time zone NOT NULL,
  modified_date timestamp with time zone,
  create_user character varying(20) NOT NULL,
  modify_user character varying(20),

  -- Radio columns
  tenant_id integer NOT NULL,
  flexnet_id bigint NOT NULL,

  -- Location columns
  address character varying(50),
  city character varying(50),
  state character varying(50),
  zip_code character varying(10),
  county character varying(50),
  timezone character varying(30),
  latitude double precision,
  longitude double precision,

  -- Rest of Light columns
  notification_history_id integer,
  pole_id character varying(30),
  protected boolean DEFAULT false,
  intensity integer DEFAULT 0,
  ecomode double precision,
  ecomode_replaced_type integer,
  ecomode_replaced_wattage double precision,
  calculate_retroactive_ecomode boolean DEFAULT false,
  blink_level integer DEFAULT 0,
  override integer DEFAULT 0,
  override_per_date timestamp with time zone,
  override_create_date timestamp with time zone,

  CONSTRAINT light_pkey PRIMARY KEY (light_id )
);

CREATE INDEX nx_light_tenant_id ON light
(
  tenant_id
);

CREATE TABLE light_tag
(
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  light_id integer NOT NULL,
  tag_id integer NOT NULL,
  CONSTRAINT light_tag_pkey PRIMARY KEY (light_id , tag_id ),
  CONSTRAINT fk_light_tag_light_id FOREIGN KEY (light_id)
      REFERENCES light (light_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT fk_light_tag_tag FOREIGN KEY (tag_id)
      REFERENCES tag (tag_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE INDEX idxlight_tag_tag_id ON light_tag USING btree (tag_id );

CREATE INDEX nx_light_tag_light_id ON light_tag USING btree (light_id);

CREATE TABLE light_grouping
(
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  grouping_id integer NOT NULL,
  light_id integer NOT NULL,
  CONSTRAINT light_grouping_pkey PRIMARY KEY (grouping_id , light_id),
  CONSTRAINT fk_light_group_group FOREIGN KEY (grouping_id)
      REFERENCES grouping (grouping_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT fk_light_group_light FOREIGN KEY (light_id)
      REFERENCES light (light_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE RESTRICT
);

ALTER TABLE light_grouping OWNER TO postgres;

CREATE INDEX nx_light_grouping_grouping_id ON light_grouping USING btree (grouping_id );

CREATE INDEX nx_light_grouping_light_id ON light_grouping USING btree (light_id);

CREATE TABLE light_daily_consumption
(
	light_id INTEGER NOT NULL,
	consumption_day DATE NOT NULL,
	consumption REAL NOT NULL,
	ecomode_baseline real,
    ecomode double precision,
	CONSTRAINT light_daily_consumption_pk PRIMARY KEY (light_id, consumption_day)
);

CREATE TABLE property_class
(
  property_class_id integer NOT NULL,
  property_class_name character varying(20) NOT NULL,
  property_class_description character varying(100),
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  PRIMARY KEY (property_class_id)
);

CREATE TABLE property
(
  property_id serial NOT NULL,
  property_name character varying(50) NOT NULL,
  label_key character varying(80) NOT NULL,
  data_type integer NOT NULL,
  create_date timestamp with time zone NOT NULL,
  modified_date timestamp with time zone,
  create_user character varying(20) NOT NULL,
  modify_user character varying(20),
  property_class smallint NOT NULL,
  has_valid_values character(1) NOT NULL,
  tenant_id integer,
  PRIMARY KEY (property_id)
);

CREATE INDEX nx_property_tenant_id ON property
(
  tenant_id
);

CREATE TABLE property_valid_value
(
  property_valid_value_id serial NOT NULL,
  valid_value character varying(4094) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  property_id integer NOT NULL,
  PRIMARY KEY (property_valid_value_id)
);

CREATE INDEX nx_property_valid_value_property_id ON property_valid_value
(
  property_id
);

CREATE TABLE light_property
(
  property_value character varying(4094),
  create_date timestamp with time zone NOT NULL,
  modified_date timestamp with time zone,
  modify_user character varying(20),
  create_user character varying(20) NOT NULL,
  light_id integer NOT NULL,
  property_id integer NOT NULL,
  property_valid_value_id integer,
  PRIMARY KEY (light_id,property_id)
);

CREATE INDEX nx_light_property_light_id ON light_property
(
  light_id
);

CREATE INDEX nx_light_property_property_id ON light_property
(
  property_id
);

CREATE INDEX nx_light_property_valid_value_id ON light_property
(
  property_valid_value_id
);

CREATE TABLE process
(
  description character varying(1000) NOT NULL,
  start_datetime timestamp with time zone NOT NULL,
  end_datetime timestamp with time zone,
  rni_correlation_id character varying(40),
  parent_process_id integer,
  is_monitored_instance boolean NOT NULL,
  estimated_seconds_to_complete bigint,
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  is_process_complete boolean NOT NULL,
  is_first_level boolean NOT NULL,
  modify_user character varying(20),
  modified_date timestamp with time zone,
  lc_action_description character varying(4094) NOT NULL,
  lc_action_id integer NOT NULL,
  tenant_id integer NOT NULL,
  process_id serial NOT NULL,
  is_submitted boolean,
  parameter_value character varying(4094),
  PRIMARY KEY (process_id)
);

CREATE UNIQUE INDEX ux_process_parent_process_id ON process
(
  parent_process_id
);

CREATE INDEX nx_process_action_id ON process
(
  lc_action_id
);

CREATE INDEX nx_process_tenant_id ON process
(
  tenant_id
);

CREATE TABLE light_process
(
  process_result integer NOT NULL,
  light_id integer NOT NULL,
  create_date timestamp with time zone,
  create_user character varying(20),
  failure_id integer,
  process_id integer NOT NULL,
  CONSTRAINT light_process_pkey PRIMARY KEY (light_id , process_id ),
  CONSTRAINT fk_failure_light_process FOREIGN KEY (failure_id)
      REFERENCES failure (failure_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT fk_process_light_process FOREIGN KEY (process_id)
      REFERENCES process (process_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT fk_light_light_process FOREIGN KEY (light_id)
      REFERENCES light (light_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE operational_data_type
(
  operational_data_type_id integer NOT NULL,
  label_key character varying(80) NOT NULL,
  unit_of_measurement character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  PRIMARY KEY (operational_data_type_id)
);

------------------------------------------------------------------------------------------------------------

/* Notification history */

CREATE SEQUENCE notification_history_status_message_id_seq;

CREATE TABLE notification_history (
	notification_history_id INTEGER NOT NULL DEFAULT nextval('notification_history_status_message_id_seq'),
	light_id INTEGER NOT NULL,
	lifecycle_state smallint NOT NULL,
	notification_type smallint NOT NULL,
	message_date TIMESTAMP NOT NULL,
	create_date TIMESTAMP NOT NULL,
	update_date TIMESTAMP NOT NULL,
	create_user VARCHAR(20) NOT NULL,
	precedence INTEGER NOT NULL,
	simple_notification BOOLEAN,
	notification_transation_id VARCHAR(40) NOT NULL,
	CONSTRAINT notification_history_id PRIMARY KEY (notification_history_id)
);

/* Table: notification_history_alert */

  CREATE TABLE notification_history_alert (
	alert_subtype_id INTEGER NOT NULL,
	notification_history_id INTEGER NOT NULL,
	create_date TIMESTAMP NOT NULL,
	update_date TIMESTAMP NOT NULL,
	message_date TIMESTAMP NOT NULL,
	create_user VARCHAR(20) NOT NULL,
	modify_user VARCHAR(20),
    modified_date TIMESTAMP,
	CONSTRAINT notification_history_pk PRIMARY KEY (alert_subtype_id, notification_history_id)
);

/* Alert Type */

CREATE TABLE alert_type (
	alert_type_id INTEGER NOT NULL,
	label_key VARCHAR(80) NOT NULL,
	create_date TIMESTAMP NOT NULL,
	create_user VARCHAR(20) NOT NULL,
	CONSTRAINT alert_type_pkey PRIMARY KEY (alert_type_id)
);

/* Alert Subtype */

CREATE TABLE alert_subtype (
	alert_subtype_id INTEGER NOT NULL,
	label_key VARCHAR(80) NOT NULL,
	create_date TIMESTAMP NOT NULL,
	create_user VARCHAR(20) NOT NULL,
	alert_type_id INTEGER NOT NULL,
	CONSTRAINT alert_subtype_pkey PRIMARY KEY (alert_subtype_id)
);

CREATE INDEX nx_alert_subtype_alert_id
 ON alert_subtype USING BTREE
 ( alert_type_id );

CREATE TABLE operational_data_value
(
  value double precision NOT NULL,
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  operational_data_type_id integer NOT NULL,
  notification_history_id integer NOT NULL,
  PRIMARY KEY (operational_data_type_id,notification_history_id,create_date)
);

CREATE INDEX nx_operational_data_value_operational_data_type_id ON operational_data_value
(
  operational_data_type_id
);

CREATE INDEX nx_operational_data_value_notification_history_id ON operational_data_value
(
  notification_history_id
);

CREATE TABLE schedule
(
  schedule_id serial NOT NULL,
  name character varying(100) NOT NULL,
  description character varying(150),
  sunrise_offset integer,
  sunset_offset integer,
  use_sunrise_sunset_tables boolean NOT NULL,
  create_date timestamp with time zone NOT NULL,
  modified_date timestamp with time zone,
  create_user character varying(20) NOT NULL,
  modify_user character varying(20),
  schedule_type smallint NOT NULL,
  tenant_id integer,
  intensity integer,
  latitude float8,
  longitude float8,
  PRIMARY KEY (schedule_id)
);

CREATE INDEX nx_schedule_tenant_id ON schedule
(
  tenant_id
);

CREATE TABLE schedule_event
(
  schedule_event_id serial NOT NULL,
  event_time timestamp with time zone NOT NULL,
  intensity integer NOT NULL,
  blink_level integer DEFAULT 0,
  create_date timestamp with time zone NOT NULL,
  modified_date timestamp with time zone,
  create_user character varying(20),
  modify_user character varying(20),
  schedule_id integer NOT NULL,
  tenant_id integer NOT NULL,
  PRIMARY KEY (schedule_event_id)
);

CREATE INDEX nx_schedule_event_schedule_id ON schedule_event
(
  schedule_id
);

CREATE INDEX nx_schedule_event_tenant_id ON schedule_event
(
  tenant_id
);

CREATE TABLE schedule_event_day_of_week
(
  create_date timestamp with time zone NOT NULL,
  modified_date timestamp with time zone,
  create_user character varying(20),
  modify_user character varying(20),
  day_of_week_id integer NOT NULL,
  schedule_event_id integer NOT NULL
);

CREATE INDEX nx_schedule_event_day_of_week_day_of_week_id ON schedule_event_day_of_week
(
  day_of_week_id
);

CREATE INDEX nx_schedule_event_day_of_week_schedule_event_id ON schedule_event_day_of_week
(
  schedule_event_id
);

CREATE TABLE schedule_membership
(
  create_date timestamp with time zone NOT NULL,
  modified_date timestamp with time zone,
  create_user character varying(20) NOT NULL,
  modify_user character varying(20),
  schedule_id integer NOT NULL,
  light_id integer,
  PRIMARY KEY (schedule_id,light_id)
);

CREATE INDEX nx_schedule_membership_schedule_id ON schedule_membership
(
  schedule_id
);

CREATE INDEX nx_schedule_membership_light_id ON schedule_membership
(
  light_id
);

CREATE TABLE action_category
(
  action_category_id serial NOT NULL,
  label_key character varying(200),
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  PRIMARY KEY (action_category_id)
);

CREATE TABLE action_category_lc_action
(
  action_category_id integer NOT NULL,
  lc_action_id integer NOT NULL,
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  PRIMARY KEY (action_category_id,lc_action_id)
);

CREATE TABLE process_property
(
  process_id integer NOT NULL,
  property_id integer NOT NULL,
  value character varying(200),
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20),
  PRIMARY KEY (process_id,property_id)
);

CREATE TABLE users
(
  user_id serial NOT NULL,
  username character varying(50) NOT NULL,
  tenant_id integer NULL,
  password character varying(250) NOT NULL,
  first_name character varying(50),
  last_name character varying(50),
  email character varying(50),
  enabled boolean NOT NULL,
  all_lights_auth boolean DEFAULT false NOT NULL,
  create_date timestamp with time zone NOT NULL,
  create_user character varying(50) NOT NULL,
  modified_date timestamp with time zone,
  modified_user character varying(50),

  PRIMARY KEY (user_id)
);

ALTER TABLE users ADD CONSTRAINT ux_users_unique_tenant_user_id UNIQUE (username,tenant_id);

CREATE UNIQUE INDEX ux_users_tenant_id_name
  ON users
  USING btree
  (tenant_id , upper(username::text) COLLATE pg_catalog."default" );

CREATE TABLE user_settings
(
  user_settings_id serial NOT NULL,
  user_id integer,
  tenant_id integer NOT NULL,
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  PRIMARY KEY (user_settings_id)
);

CREATE INDEX nx_user_settings_user_id ON user_settings
(
  user_id
);

CREATE INDEX nx_user_settings_tenant_id ON user_settings
(
  tenant_id
);

CREATE UNIQUE INDEX ux_tenant_id_user_id_key ON user_settings
(
  tenant_id,
  user_id
);

CREATE TABLE user_settings_property
(
  user_settings_property serial NOT NULL,
  user_settings_id integer NOT NULL,
  property_id integer NOT NULL,
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  modified_date timestamp with time zone,
  modify_user character varying(20),
  user_setting_property_value character varying(4094),
  display_order integer NULL,
  PRIMARY KEY (user_settings_property)
);

CREATE TABLE custom_search
(
  custom_search_id serial NOT NULL,
  custom_search_name character varying(40) NOT NULL,
  custom_search_description character varying(200),
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  modified_date timestamp with time zone,
  modified_user character varying(20),
  user_id integer NOT NULL,
  tenant_id integer,
  PRIMARY KEY (custom_search_id)
);

CREATE INDEX nx_custom_search_user_id ON custom_search
(
  user_id
);

CREATE INDEX nx_custom_search_tenant_id ON custom_search
(
  tenant_id
);

CREATE TABLE operator
(
  operator_id integer NOT NULL,
  operator_code character varying(20) NOT NULL,
  operator_description character varying(100),
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  PRIMARY KEY (operator_id)
);

CREATE TABLE custom_search_property
(
  custom_search_property_id serial NOT NULL,
  custom_search_id integer NOT NULL,
  property_id integer NOT NULL,
  create_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  modified_date timestamp with time zone,
  modified_user character varying(20),
  custom_search_property_value character varying(4094),
  operator_id integer,
  display_order integer NULL,
  PRIMARY KEY (custom_search_property_id)
);

CREATE INDEX nx_custom_search_property_operator_id ON custom_search_property
(
  operator_id
);

CREATE TABLE analytics_group
(
  analytic_group_id serial NOT NULL,
  analytic_group_name character varying(100) NOT NULL,
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  tenant_id integer,
  grouping_id integer,
  PRIMARY KEY (analytic_group_id)
);

CREATE UNIQUE INDEX ux_analytics_group_analytic_group_name ON analytics_group
(
  analytic_group_name,
  tenant_id
);

CREATE TABLE analytics_group_by_date
(
  analytic_group_by_date_id serial NOT NULL,
  analytic_group_id integer NOT NULL,
  analytic_date timestamp with time zone NOT NULL,
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  PRIMARY KEY (analytic_group_by_date_id)
);

CREATE INDEX nx_analytics_group_by_date_analytics_group ON analytics_group_by_date
(
  analytic_group_id
);

CREATE TABLE analytics_light_type
(
  light_type_id integer NOT NULL,
  light_type_name character varying(10) NOT NULL,
  label_key character varying(80) NOT NULL,
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  PRIMARY KEY (light_type_id)
);

CREATE TABLE analytics_consumption
(
  id serial NOT NULL,
  light_type_id integer NOT NULL,
  value real NOT NULL,
  analytic_group_by_date_id integer NOT NULL,
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX nx_analytics_consumption_light_type ON analytics_consumption
(
  light_type_id
);

CREATE INDEX nx_analytics_consumption_analytic_group_by_date ON analytics_consumption
(
  analytic_group_by_date_id
);

CREATE TABLE analytics_installed
(
  id serial NOT NULL,
  light_type_id integer NOT NULL,
  value integer NOT NULL,
  analytic_group_by_date_id integer NOT NULL,
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX nx_analytics_installed_analytic_group_by_date ON analytics_installed
(
  analytic_group_by_date_id
);

CREATE INDEX nx_analytics_installed_light_type ON analytics_installed
(
  light_type_id
);

CREATE TABLE analytics_alarm_warning_subtype
(
  analytics_alarm_warning_subtype_id integer NOT NULL,
  label_key character varying(80) NOT NULL,
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  PRIMARY KEY (analytics_alarm_warning_subtype_id)
);

CREATE TABLE analytics_alarms
(
  id serial NOT NULL,
  light_type_id integer NOT NULL,
  value integer NOT NULL,
  analytic_group_by_date_id integer NOT NULL,
  analytics_alarm_subtype integer NOT NULL,
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX nx_analytics_alarms_light_type ON analytics_alarms
(
  light_type_id
);

CREATE INDEX nx_analytics_alarms_analytic_group_by_date ON analytics_alarms
(
  analytic_group_by_date_id
);

CREATE INDEX nx_analytics_alarms_analytics_alarm_warning_subtype ON analytics_alarms
(
  analytics_alarm_subtype
);

CREATE TABLE analytics_warnings
(
  id serial NOT NULL,
  light_type_id integer NOT NULL,
  value integer NOT NULL,
  analytic_group_by_date_id integer NOT NULL,
  analytics_warning_subtype integer NOT NULL,
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX nx_analytics_warnings_analytic_group_by_date ON analytics_warnings
(
  analytic_group_by_date_id
);

CREATE INDEX nx_analytics_warnings_light_type ON analytics_warnings
(
  light_type_id
);

CREATE INDEX nx_analytics_warnings_analytics_alarm_warning_subtype ON analytics_warnings
(
  analytics_warning_subtype
);

CREATE TABLE users_grouping
(
  user_id integer NOT NULL,
  grouping_id integer NOT NULL,
  create_user character varying(50),
  create_date timestamp with time zone,
  PRIMARY KEY (user_id,grouping_id)
);

CREATE TABLE dashboard_resume
(
  tenant_id INTEGER NOT NULL,
  analytics_type CHARACTER VARYING(1) NOT NULL,
  grouping_id INTEGER,
  view_mode CHARACTER VARYING(20) NOT NULL,
  value REAL NOT NULL,
  average REAL NOT NULL,
  change REAL NOT NULL,
  trends CHARACTER VARYING(500) NOT NULL,
  create_date TIMESTAMP WITH TIME ZONE NOT NULL,
  create_user CHARACTER VARYING(20) NOT NULL
);

CREATE TABLE dashboard_resume_chart
(
  tenant_id integer NOT NULL,
  grouping_id integer,
  alert_subtype_id integer NOT NULL,
  amount integer NOT NULL
);

CREATE TABLE authorities
(
  user_id integer NOT NULL,
  authority character varying(50) NOT NULL
);

CREATE INDEX ix_auth_username ON authorities
(
  user_id,
  authority
);

CREATE TABLE analytics_ecomode
(
  id serial NOT NULL,
  analytic_group_by_date_id integer NOT NULL,
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  ecomode_percent double precision not null,
  ecomode_measured double precision not null,
  ecomode_baseline double precision not null,
  CONSTRAINT analytics_ecomode_pkey PRIMARY KEY (id),
  CONSTRAINT fk_analytics_ecomode_analytics_group_by_date FOREIGN KEY (analytic_group_by_date_id)
      REFERENCES analytics_group_by_date (analytic_group_by_date_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE analytics_eco_mode_type
(
  eco_mode_id integer NOT NULL,
  eco_mode_type_name character varying(25) NOT NULL,
  label_key character varying(80) NOT NULL,
  create_user character varying(20) NOT NULL,
  create_date timestamp with time zone NOT NULL,
  PRIMARY KEY (eco_mode_id)
);

CREATE TABLE analytics_alarms_summarized
(
  date_time timestamp without time zone NOT NULL,
  lamp_failure integer NULL,
  power_failure integer NULL,
  board_failure integer NULL,
  metrology_error integer NULL,
  metrology_com_failure integer NULL,
  group_id integer NOT NULL,
  range_date integer NOT NULL,
  tenant_id integer NOT NULL
);

CREATE TABLE analytics_warnings_summarized
(
  date_time timestamp without time zone NOT NULL,
  power_surge_detected integer NULL,
  brownout_detected integer NULL,
  communication_fail integer NULL,
  high_current integer NULL,
  low_current integer NULL,
  reverse_energy integer NULL,
  metrology_reset integer NULL,
  group_id integer NOT NULL,
  range_date integer NOT NULL,
  tenant_id integer NOT NULL
);

CREATE TABLE analytics_installed_summarized
(
  date_time timestamp without time zone NOT NULL,
  induction integer NULL,
  led integer NULL,
  other integer NULL,
  group_id integer NOT NULL,
  range_date integer NOT NULL,
  tenant_id integer NOT NULL
);

CREATE INDEX idx_alarm_group_id
  ON analytics_alarms_summarized
  USING btree
  (group_id);

CREATE INDEX idx_alarm_range_date
  ON analytics_alarms_summarized
  USING btree
  (range_date);

 CREATE INDEX idx_warnings_group_id
  ON analytics_warnings_summarized
  USING btree
  (group_id);

CREATE INDEX idx_warnings_range_date
  ON analytics_warnings_summarized
  USING btree
  (range_date);

CREATE INDEX idx_installed_group_id
  ON analytics_installed_summarized
  USING btree
  (group_id);

CREATE INDEX idx_installed_range_date
  ON analytics_installed_summarized
  USING btree
  (range_date);

ALTER TABLE failure ADD CONSTRAINT fk_lc_action_failure
  FOREIGN KEY ( lc_action_id )
   REFERENCES lc_action ( lc_action_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE grouping ADD CONSTRAINT fk_tenant_grouping
  FOREIGN KEY ( tenant_id )
   REFERENCES tenant ( tenant_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE light ADD CONSTRAINT fk_tenant_light
  FOREIGN KEY ( tenant_id )
   REFERENCES tenant ( tenant_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE light_property ADD CONSTRAINT fk_light_property_value
  FOREIGN KEY ( light_id )
   REFERENCES light ( light_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE light_property ADD CONSTRAINT fk_property_property_value
  FOREIGN KEY ( property_id )
   REFERENCES property ( property_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE light_property ADD CONSTRAINT fk_property_valid_value_light_property
  FOREIGN KEY ( property_valid_value_id )
   REFERENCES property_valid_value ( property_valid_value_id )
    ON DELETE SET NULL NOT DEFERRABLE;
ALTER TABLE process ADD CONSTRAINT fk_lc_action_process
  FOREIGN KEY ( lc_action_id )
   REFERENCES lc_action ( lc_action_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE process ADD CONSTRAINT fk_tenant_process
  FOREIGN KEY ( tenant_id )
   REFERENCES tenant ( tenant_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE operational_data_value ADD CONSTRAINT fk_operational_data_type_operational_data_value
  FOREIGN KEY ( operational_data_type_id )
   REFERENCES operational_data_type ( operational_data_type_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE operational_data_value ADD CONSTRAINT fk_status_message_operational_data_value
  FOREIGN KEY ( notification_history_id )
   REFERENCES notification_history ( notification_history_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE property ADD CONSTRAINT fk_tenant_property
  FOREIGN KEY ( tenant_id )
   REFERENCES tenant ( tenant_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE property_valid_value ADD CONSTRAINT fk_property_property_valid_value
  FOREIGN KEY ( property_id )
   REFERENCES property ( property_id )
    ON DELETE SET NULL NOT DEFERRABLE;
ALTER TABLE schedule ADD CONSTRAINT fk_tenant_schedule
  FOREIGN KEY ( tenant_id )
   REFERENCES tenant ( tenant_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE schedule_event ADD CONSTRAINT fk_schedule_event_schedule
  FOREIGN KEY ( schedule_id )
   REFERENCES schedule ( schedule_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE schedule_event ADD CONSTRAINT fk_tenant_schedule_event
  FOREIGN KEY ( tenant_id )
   REFERENCES tenant ( tenant_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE schedule_event_day_of_week ADD CONSTRAINT fk_schedule_event_day_of_week_day_of_week
  FOREIGN KEY ( day_of_week_id )
   REFERENCES day_of_week ( day_of_week_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE schedule_event_day_of_week ADD CONSTRAINT fk_schedule_event_day_of_week_schedule_event
  FOREIGN KEY ( schedule_event_id )
   REFERENCES schedule_event ( schedule_event_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE schedule_membership ADD CONSTRAINT fk_schedule_membership_schedule
  FOREIGN KEY ( schedule_id )
   REFERENCES schedule ( schedule_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE schedule_membership ADD CONSTRAINT fk_schedule_membership_light_id
  FOREIGN KEY ( light_id )
   REFERENCES light ( light_id )
    ON DELETE RESTRICT NOT DEFERRABLE;

------------------------------------------------------------------------------------------------------------

ALTER SEQUENCE notification_history_status_message_id_seq OWNED BY notification_history.notification_history_id;

ALTER TABLE notification_history_alert ADD CONSTRAINT notification_history_notification_history_alert_fk
FOREIGN KEY (notification_history_id)
REFERENCES notification_history (notification_history_id)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE notification_history_alert ADD CONSTRAINT alert_subtype_notification_history_alert_fk
FOREIGN KEY (alert_subtype_id)
REFERENCES alert_subtype (alert_subtype_id)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE alert_subtype ADD CONSTRAINT fk_alert_type_alert_subtype
FOREIGN KEY (alert_type_id)
REFERENCES alert_type (alert_type_id)
ON DELETE RESTRICT
ON UPDATE NO ACTION
NOT DEFERRABLE;

------------------------------------------------------------------------------------------------------------

ALTER TABLE tag ADD CONSTRAINT fk_tenant_tag
  FOREIGN KEY ( tenant_id )
   REFERENCES tenant ( tenant_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE process ADD CONSTRAINT fk_process_process
  FOREIGN KEY ( parent_process_id )
   REFERENCES process ( process_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE action_category_lc_action ADD CONSTRAINT fk_action_category_lc_action_lc_action_id
  FOREIGN KEY ( lc_action_id )
   REFERENCES lc_action ( lc_action_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE action_category_lc_action ADD CONSTRAINT fk_action_category_process_action_category
  FOREIGN KEY ( action_category_id )
   REFERENCES action_category ( action_category_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE process_property ADD CONSTRAINT fk_process_property_process
  FOREIGN KEY ( process_id )
   REFERENCES process ( process_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE process_property ADD CONSTRAINT fk_process_property_property
  FOREIGN KEY ( property_id )
   REFERENCES property ( property_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE user_settings ADD CONSTRAINT fk_user_settings_users
  FOREIGN KEY ( user_id )
   REFERENCES users ( user_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE user_settings ADD CONSTRAINT fk_user_settings_tenant_id
  FOREIGN KEY ( tenant_id )
   REFERENCES tenant ( tenant_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE user_settings_property ADD CONSTRAINT fk_user_settings_property_user_settings_id
  FOREIGN KEY ( user_settings_id )
   REFERENCES user_settings ( user_settings_id )
    NOT DEFERRABLE;
ALTER TABLE user_settings_property ADD CONSTRAINT fk_user_settings_property_property_id
  FOREIGN KEY ( property_id )
   REFERENCES property ( property_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE property ADD CONSTRAINT fk_property_class_property
  FOREIGN KEY ( property_class )
   REFERENCES property_class ( property_class_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE custom_search_property ADD CONSTRAINT fk_custom_search_property_custom_search_id
  FOREIGN KEY ( custom_search_id )
   REFERENCES custom_search ( custom_search_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE custom_search_property ADD CONSTRAINT fk_custom_search_property_property_id
  FOREIGN KEY ( property_id )
   REFERENCES property ( property_id )
    NOT DEFERRABLE;
ALTER TABLE custom_search_property ADD CONSTRAINT fk_operator_custom_search_property
  FOREIGN KEY ( operator_id )
   REFERENCES operator ( operator_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE analytics_consumption ADD CONSTRAINT fk_analytics_consumption_analytics_group_by_date
  FOREIGN KEY ( analytic_group_by_date_id )
   REFERENCES analytics_group_by_date ( analytic_group_by_date_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE analytics_installed ADD CONSTRAINT fk_analytics_installed_analytics_group_by_date
  FOREIGN KEY ( analytic_group_by_date_id )
   REFERENCES analytics_group_by_date ( analytic_group_by_date_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE analytics_alarms ADD CONSTRAINT fk_analytics_alarms_analytics_group_by_date
  FOREIGN KEY ( analytic_group_by_date_id )
   REFERENCES analytics_group_by_date ( analytic_group_by_date_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE analytics_warnings ADD CONSTRAINT fk_analytics_consumption_analytics_group_by_date
  FOREIGN KEY ( analytic_group_by_date_id )
   REFERENCES analytics_group_by_date ( analytic_group_by_date_id )
    ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE analytics_alarms ADD CONSTRAINT fk_analytics_alarms_analytics_light_type
  FOREIGN KEY ( light_type_id )
   REFERENCES analytics_light_type ( light_type_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE analytics_installed ADD CONSTRAINT fk_analytics_installed_analytics_light_type
  FOREIGN KEY ( light_type_id )
   REFERENCES analytics_light_type ( light_type_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE analytics_warnings ADD CONSTRAINT fk_analytics_warnings_analytics_light_type
  FOREIGN KEY ( light_type_id )
   REFERENCES analytics_light_type ( light_type_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE analytics_consumption ADD CONSTRAINT fk_analytics_consumption_analytics_light_type
  FOREIGN KEY ( light_type_id )
   REFERENCES analytics_light_type ( light_type_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE analytics_group_by_date ADD CONSTRAINT fk_analytics_group_by_date_analytics_group
  FOREIGN KEY ( analytic_group_id )
   REFERENCES analytics_group ( analytic_group_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE analytics_warnings ADD CONSTRAINT fk_analytics_warnings_analytics_alarm_warning_subtype
  FOREIGN KEY ( analytics_warning_subtype )
   REFERENCES analytics_alarm_warning_subtype ( analytics_alarm_warning_subtype_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE analytics_alarms ADD CONSTRAINT fk_analytics_alarms_analytics_alarm_warning_subtype
  FOREIGN KEY ( analytics_alarm_subtype )
   REFERENCES analytics_alarm_warning_subtype ( analytics_alarm_warning_subtype_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE custom_search ADD CONSTRAINT fk_custom_search_tenant_id
  FOREIGN KEY ( tenant_id )
   REFERENCES tenant ( tenant_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE custom_search ADD CONSTRAINT fk_custom_search_users
  FOREIGN KEY ( user_id )
   REFERENCES users ( user_id )
    ON DELETE RESTRICT NOT DEFERRABLE;
ALTER TABLE users_grouping ADD CONSTRAINT fk_users_grouping_users
  FOREIGN KEY ( user_id )
   REFERENCES users ( user_id )
    NOT DEFERRABLE;
ALTER TABLE users_grouping ADD CONSTRAINT fk_users_grouping_grouping
  FOREIGN KEY ( grouping_id )
   REFERENCES grouping ( grouping_id )
    NOT DEFERRABLE;
ALTER TABLE authorities ADD CONSTRAINT fk_authorities_users
  FOREIGN KEY ( user_id )
   REFERENCES users ( user_id )
    NOT DEFERRABLE;

ALTER TABLE light_daily_consumption ADD CONSTRAINT fk_light_light_daily_consumption
	FOREIGN KEY (light_id)
	 REFERENCES public.light (light_id)
      NOT DEFERRABLE;

ALTER TABLE light_configuration ADD CONSTRAINT fk_light_light_configuration
	FOREIGN KEY (light_id)
	 REFERENCES light (light_id)
	  ON DELETE NO ACTION
	  ON UPDATE NO ACTION
	  NOT DEFERRABLE;

ALTER TABLE light_last_operational_data ADD CONSTRAINT fk_light_light_last_op_data
	FOREIGN KEY (light_id)
	 REFERENCES light (light_id)
	  ON DELETE NO ACTION
	  ON UPDATE NO ACTION
	  NOT DEFERRABLE;

ALTER TABLE light_schedule ADD CONSTRAINT fk_light_light_schedule
	FOREIGN KEY (light_id)
	 REFERENCES light (light_id)
	  ON DELETE NO ACTION
	  ON UPDATE NO ACTION
	  NOT DEFERRABLE;

ALTER TABLE schedule_membership ADD CONSTRAINT fk_schedule_membership_light
	FOREIGN KEY (light_id)
	 REFERENCES light (light_id)
	  ON UPDATE NO ACTION
	  ON DELETE NO ACTION;

ALTER TABLE api_control  ADD CONSTRAINT tenant_api_control_request_fk
    FOREIGN KEY (tenant_id)
     REFERENCES tenant (tenant_id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;

-------------------------------------------------------------------------------------------------------------

/* Light Sequence */
CREATE SEQUENCE light_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;