
CREATE TABLE NOTAS (
    xMotivo VARCHAR(99),
    chNFe VARCHAR(50) not null,
    dhRecbto VARCHAR(50),
    nProt VARCHAR(50),
    ide_mod VARCHAR(05),
    ide_natOp VARCHAR(99),
    ide_nNF VARCHAR(20),
    ide_serie VARCHAR(20),
    ide_tpImp VARCHAR(20),
    ide_tpEmis VARCHAR(20),
    ide_cDV VARCHAR(20),
    ide_tpAmb VARCHAR(20),
    ide_dEmi VARCHAR(20),
    ide_dSaiEnt VARCHAR(20),
    ide_hSaiEnt VARCHAR(20),
    emit_xNome VARCHAR(99),
    emit_CNPJ VARCHAR(30),
    emit_IE VARCHAR(30),
    emit_CRT VARCHAR(05),
    enderEmit_xLgr VARCHAR(99),
    enderEmit_nro VARCHAR(20),
    enderEmit_xBairro VARCHAR(99),
    enderEmit_xMun VARCHAR(99),
    enderEmit_CEP VARCHAR(20),
    enderEmit_fone VARCHAR(20),
    enderEmit_UF VARCHAR(05),
    dest_xNome VARCHAR(99),
    dest_CNPJ VARCHAR(30),
    dest_CPF VARCHAR(30),
    dest_IE VARCHAR(30),
    dest_email VARCHAR(99),
    enderDest_xLgr VARCHAR(99),
    enderDest_nro VARCHAR(20),
    enderDest_xBairro VARCHAR(99),
    enderDest_xMun VARCHAR(99),
    enderDest_CEP VARCHAR(20),
    enderDest_fone VARCHAR(30),
    enderDest_UF VARCHAR(05),
    Xml  VARCHAR(10000)
);

ALTER TABLE NOTAS ADD CONSTRAINT NOTAS PRIMARY KEY (chNFe);