INSERT INTO estado(nome,abreviacao)values
('Ceara','CE'),
('Pernambuco','PE'),
('Alaguas','AL'),
('Sergipe','SE'),
('Bahia','BA'),
('Minas Gerais','MG'),
('Espirito Santo','ES'),
('Rio de janeiro','RJ'),
('São Paulo','SP'),
('Parana','PR'),
('Santa Catarina','SC'),
('Rio Grande do Sul','RS'),
('Mato grosso do sul','MS'),
('Teste','MS'),
('Goias','GO'),
('Distrito Federal','DF'),
('Distrito Federal','RN'),
('Distrito Federal','PB');