
INSERT INTO NFNotaInfoItemImpostoICMSPartilhado( id, origem, situacaoTributaria, modalidadeBCICMS, valorBCICMS, percentualReducaoBC, percentualAliquotaImposto, valorICMS, modalidadeBCICMSST, percentualMargemValorAdicionadoICMSST, percentualReducaoBCICMSST, valorBCICMSST, percentualAliquotaImpostoICMSST, valorICMSST, percentualBCOperacaoPropria, ufICMSST,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1000, 1000, 1000, 1000, 'valorBCICMS_0', 'percentualReducaoBC_0', 'percentualAliquotaImposto_0', 'valorICMS_0', 1000, 'percentualMargemValorAdicionadoICMSST_0', 'percentualReducaoBCICMSST_0', 'valorBCICMSST_0', 'percentualAliquotaImpostoICMSST_0', 'valorICMSST_0', 'percentualBCOperacaoPropria_0', 1000,10000,1,1,1,'system',1480868161263,'rod',1480868161263);

INSERT INTO NFNotaInfoItemImpostoICMSPartilhado( id, origem, situacaoTributaria, modalidadeBCICMS, valorBCICMS, percentualReducaoBC, percentualAliquotaImposto, valorICMS, modalidadeBCICMSST, percentualMargemValorAdicionadoICMSST, percentualReducaoBCICMSST, valorBCICMSST, percentualAliquotaImpostoICMSST, valorICMSST, percentualBCOperacaoPropria, ufICMSST,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1001, 1001, 1001, 1001, 'valorBCICMS_1', 'percentualReducaoBC_1', 'percentualAliquotaImposto_1', 'valorICMS_1', 1001, 'percentualMargemValorAdicionadoICMSST_1', 'percentualReducaoBCICMSST_1', 'valorBCICMSST_1', 'percentualAliquotaImpostoICMSST_1', 'valorICMSST_1', 'percentualBCOperacaoPropria_1', 1001,10000,1,1,1,'system',1480868161263,'rod',1480868161263);

INSERT INTO NFNotaInfoItemImpostoICMSPartilhado( id, origem, situacaoTributaria, modalidadeBCICMS, valorBCICMS, percentualReducaoBC, percentualAliquotaImposto, valorICMS, modalidadeBCICMSST, percentualMargemValorAdicionadoICMSST, percentualReducaoBCICMSST, valorBCICMSST, percentualAliquotaImpostoICMSST, valorICMSST, percentualBCOperacaoPropria, ufICMSST,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1002, 1002, 1002, 1002, 'valorBCICMS_2', 'percentualReducaoBC_2', 'percentualAliquotaImposto_2', 'valorICMS_2', 1002, 'percentualMargemValorAdicionadoICMSST_2', 'percentualReducaoBCICMSST_2', 'valorBCICMSST_2', 'percentualAliquotaImpostoICMSST_2', 'valorICMSST_2', 'percentualBCOperacaoPropria_2', 1002,10000,1,1,1,'system',1480868161263,'rod',1480868161263);
