
INSERT INTO NFNotaInfoItemImpostoISSQN( id, valorBaseCalculo, valorAliquota, valor, codigoMunicipio, itemListaServicos, valorDeducao, valorOutro, valorDescontoIncondicionado, valorDescontoCondicionado, valorRetencaoISS, indicadorExigibilidadeISS, codigoServico, codigoMunicipioIncidenciaImposto, codigoPais, numeroProcesso, indicadorIncentivoFiscal,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1000, 'valorBaseCalculo_0', 'valorAliquota_0', 'valor_0', 1000, 'itemListaServicos_0', 'valorDeducao_0', 'valorOutro_0', 'valorDescontoIncondicionado_0', 'valorDescontoCondicionado_0', 'valorRetencaoISS_0', 1000, 'codigoServico_0', 'codigoMunicipioIncidenciaImposto_0', 'codigoPais_0', 'numeroProcesso_0', 1000,10000,1,1,1,'system',1480868161268,'rod',1480868161268);

INSERT INTO NFNotaInfoItemImpostoISSQN( id, valorBaseCalculo, valorAliquota, valor, codigoMunicipio, itemListaServicos, valorDeducao, valorOutro, valorDescontoIncondicionado, valorDescontoCondicionado, valorRetencaoISS, indicadorExigibilidadeISS, codigoServico, codigoMunicipioIncidenciaImposto, codigoPais, numeroProcesso, indicadorIncentivoFiscal,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1001, 'valorBaseCalculo_1', 'valorAliquota_1', 'valor_1', 1001, 'itemListaServicos_1', 'valorDeducao_1', 'valorOutro_1', 'valorDescontoIncondicionado_1', 'valorDescontoCondicionado_1', 'valorRetencaoISS_1', 1001, 'codigoServico_1', 'codigoMunicipioIncidenciaImposto_1', 'codigoPais_1', 'numeroProcesso_1', 1001,10000,1,1,1,'system',1480868161268,'rod',1480868161268);

INSERT INTO NFNotaInfoItemImpostoISSQN( id, valorBaseCalculo, valorAliquota, valor, codigoMunicipio, itemListaServicos, valorDeducao, valorOutro, valorDescontoIncondicionado, valorDescontoCondicionado, valorRetencaoISS, indicadorExigibilidadeISS, codigoServico, codigoMunicipioIncidenciaImposto, codigoPais, numeroProcesso, indicadorIncentivoFiscal,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1002, 'valorBaseCalculo_2', 'valorAliquota_2', 'valor_2', 1002, 'itemListaServicos_2', 'valorDeducao_2', 'valorOutro_2', 'valorDescontoIncondicionado_2', 'valorDescontoCondicionado_2', 'valorRetencaoISS_2', 1002, 'codigoServico_2', 'codigoMunicipioIncidenciaImposto_2', 'codigoPais_2', 'numeroProcesso_2', 1002,10000,1,1,1,'system',1480868161268,'rod',1480868161268);
