
INSERT INTO NFNotaInfoItemImpostoICMS70( id, origem, situacaoTributaria, modalidadeBCICMS, percentualReducaoBC, valorBC, percentualAliquota, valorTributo, modalidadeBCICMSST, percentualMargemValorAdicionadoICMSST, percentualReducaoBCICMSST, valorBCST, percentualAliquotaImpostoICMSST, valorICMSST, valorICMSDesoneracao, desoneracao,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1000, 1000, 1000, 1000, 'percentualReducaoBC_0', 'valorBC_0', 'percentualAliquota_0', 'valorTributo_0', 'modalidadeBCICMSST_0', 'percentualMargemValorAdicionadoICMSST_0', 'percentualReducaoBCICMSST_0', 'valorBCST_0', 'percentualAliquotaImpostoICMSST_0', 'valorICMSST_0', 'valorICMSDesoneracao_0', 'desoneracao_0',10000,1,1,1,'system',1480868161262,'rod',1480868161262);

INSERT INTO NFNotaInfoItemImpostoICMS70( id, origem, situacaoTributaria, modalidadeBCICMS, percentualReducaoBC, valorBC, percentualAliquota, valorTributo, modalidadeBCICMSST, percentualMargemValorAdicionadoICMSST, percentualReducaoBCICMSST, valorBCST, percentualAliquotaImpostoICMSST, valorICMSST, valorICMSDesoneracao, desoneracao,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1001, 1001, 1001, 1001, 'percentualReducaoBC_1', 'valorBC_1', 'percentualAliquota_1', 'valorTributo_1', 'modalidadeBCICMSST_1', 'percentualMargemValorAdicionadoICMSST_1', 'percentualReducaoBCICMSST_1', 'valorBCST_1', 'percentualAliquotaImpostoICMSST_1', 'valorICMSST_1', 'valorICMSDesoneracao_1', 'desoneracao_1',10000,1,1,1,'system',1480868161262,'rod',1480868161262);

INSERT INTO NFNotaInfoItemImpostoICMS70( id, origem, situacaoTributaria, modalidadeBCICMS, percentualReducaoBC, valorBC, percentualAliquota, valorTributo, modalidadeBCICMSST, percentualMargemValorAdicionadoICMSST, percentualReducaoBCICMSST, valorBCST, percentualAliquotaImpostoICMSST, valorICMSST, valorICMSDesoneracao, desoneracao,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1002, 1002, 1002, 1002, 'percentualReducaoBC_2', 'valorBC_2', 'percentualAliquota_2', 'valorTributo_2', 'modalidadeBCICMSST_2', 'percentualMargemValorAdicionadoICMSST_2', 'percentualReducaoBCICMSST_2', 'valorBCST_2', 'percentualAliquotaImpostoICMSST_2', 'valorICMSST_2', 'valorICMSDesoneracao_2', 'desoneracao_2',10000,1,1,1,'system',1480868161262,'rod',1480868161262);
