
INSERT INTO NFNotaInfoItemImpostoICMSUFDestino( id, valorBaseCalculoDestino, percentualRelativoFundoCombatePobrezaDestino, percentualAliquotaInternaDestino, percentualInterestadual, percentualProvisorioPartilha, valorRelativoFundoCombatePobrezaDestino, valorICMSInterestadualDestino, valorICMSInterestadualRemetente,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1000, 'valorBaseCalculoDestino_0', 'percentualRelativoFundoCombatePobrezaDestino_0', 'percentualAliquotaInternaDestino_0', 'percentualInterestadual_0', 'percentualProvisorioPartilha_0', 'valorRelativoFundoCombatePobrezaDestino_0', 'valorICMSInterestadualDestino_0', 'valorICMSInterestadualRemetente_0',10000,1,1,1,'system',1480868161273,'rod',1480868161273);

INSERT INTO NFNotaInfoItemImpostoICMSUFDestino( id, valorBaseCalculoDestino, percentualRelativoFundoCombatePobrezaDestino, percentualAliquotaInternaDestino, percentualInterestadual, percentualProvisorioPartilha, valorRelativoFundoCombatePobrezaDestino, valorICMSInterestadualDestino, valorICMSInterestadualRemetente,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1001, 'valorBaseCalculoDestino_1', 'percentualRelativoFundoCombatePobrezaDestino_1', 'percentualAliquotaInternaDestino_1', 'percentualInterestadual_1', 'percentualProvisorioPartilha_1', 'valorRelativoFundoCombatePobrezaDestino_1', 'valorICMSInterestadualDestino_1', 'valorICMSInterestadualRemetente_1',10000,1,1,1,'system',1480868161273,'rod',1480868161273);

INSERT INTO NFNotaInfoItemImpostoICMSUFDestino( id, valorBaseCalculoDestino, percentualRelativoFundoCombatePobrezaDestino, percentualAliquotaInternaDestino, percentualInterestadual, percentualProvisorioPartilha, valorRelativoFundoCombatePobrezaDestino, valorICMSInterestadualDestino, valorICMSInterestadualRemetente,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1002, 'valorBaseCalculoDestino_2', 'percentualRelativoFundoCombatePobrezaDestino_2', 'percentualAliquotaInternaDestino_2', 'percentualInterestadual_2', 'percentualProvisorioPartilha_2', 'valorRelativoFundoCombatePobrezaDestino_2', 'valorICMSInterestadualDestino_2', 'valorICMSInterestadualRemetente_2',10000,1,1,1,'system',1480868161273,'rod',1480868161273);
