
INSERT INTO NFNotaInfoISSQNTotal( id, valorTotalServicosSobNaoIncidenciaNaoTributadosICMS, baseCalculoISS, valorTotalISS, valorPISsobreServicos, valorCOFINSsobreServicos, dataPrestacaoServico, valorDeducao, valorOutros, valorTotalDescontoIncondicionado, valorTotalDescontoCondicionado, valorTotalRetencaoISS, tributacao,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1000, 'valorTotalServicosSobNaoIncidenciaNaoTributadosICMS_0', 'baseCalculoISS_0', 'valorTotalISS_0', 'valorPISsobreServicos_0', 'valorCOFINSsobreServicos_0',  1475163820865 , 'valorDeducao_0', 'valorOutros_0', 'valorTotalDescontoIncondicionado_0', 'valorTotalDescontoCondicionado_0', 'valorTotalRetencaoISS_0', 1000,10000,1,1,1,'system',1475163820865,'rod',1475163820865);

INSERT INTO NFNotaInfoISSQNTotal( id, valorTotalServicosSobNaoIncidenciaNaoTributadosICMS, baseCalculoISS, valorTotalISS, valorPISsobreServicos, valorCOFINSsobreServicos, dataPrestacaoServico, valorDeducao, valorOutros, valorTotalDescontoIncondicionado, valorTotalDescontoCondicionado, valorTotalRetencaoISS, tributacao,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1001, 'valorTotalServicosSobNaoIncidenciaNaoTributadosICMS_1', 'baseCalculoISS_1', 'valorTotalISS_1', 'valorPISsobreServicos_1', 'valorCOFINSsobreServicos_1',  1475163820865 , 'valorDeducao_1', 'valorOutros_1', 'valorTotalDescontoIncondicionado_1', 'valorTotalDescontoCondicionado_1', 'valorTotalRetencaoISS_1', 1001,10000,1,1,1,'system',1475163820865,'rod',1475163820865);

INSERT INTO NFNotaInfoISSQNTotal( id, valorTotalServicosSobNaoIncidenciaNaoTributadosICMS, baseCalculoISS, valorTotalISS, valorPISsobreServicos, valorCOFINSsobreServicos, dataPrestacaoServico, valorDeducao, valorOutros, valorTotalDescontoIncondicionado, valorTotalDescontoCondicionado, valorTotalRetencaoISS, tributacao,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1002, 'valorTotalServicosSobNaoIncidenciaNaoTributadosICMS_2', 'baseCalculoISS_2', 'valorTotalISS_2', 'valorPISsobreServicos_2', 'valorCOFINSsobreServicos_2',  1475163820865 , 'valorDeducao_2', 'valorOutros_2', 'valorTotalDescontoIncondicionado_2', 'valorTotalDescontoCondicionado_2', 'valorTotalRetencaoISS_2', 1002,10000,1,1,1,'system',1475163820865,'rod',1475163820865);
