
INSERT INTO NFNotaInfoItemProduto( id, codigo, codigoDeBarras, descricao, ncm, codigoEspecificadorSituacaoTributaria, extipi, cfop, unidadeComercial, quantidadeComercial, valorUnitario, valorTotalBruto, codigoDeBarrasTributavel, unidadeTributavel, quantidadeTributavel, valorUnitarioTributavel, valorFrete, valorSeguro, valorDesconto, valorOutrasDespesasAcessorias, compoeValorNota, numeroPedidoCliente, numeroPedidoItemCliente, numeroControleFCI, veiculo, combustivel, numeroRECOPI,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1000, 'codigo_0', 'codigoDeBarras_0', 'descricao_0', 'ncm_0', 'codigoEspecificadorSituacaoTributaria_0', 'extipi_0', 'cfop_0', 'unidadeComercial_0', 'quantidadeComercial_0', 'valorUnitario_0', 'valorTotalBruto_0', 'codigoDeBarrasTributavel_0', 'unidadeTributavel_0', 'quantidadeTributavel_0', 'valorUnitarioTributavel_0', 'valorFrete_0', 'valorSeguro_0', 'valorDesconto_0', 'valorOutrasDespesasAcessorias_0', 1000, 'numeroPedidoCliente_0', 1000, 'numeroControleFCI_0', 1000, 1000, 'numeroRECOPI_0',10000,1,1,1,'system',1480868161253,'rod',1480868161253);

INSERT INTO NFNotaInfoItemProduto( id, codigo, codigoDeBarras, descricao, ncm, codigoEspecificadorSituacaoTributaria, extipi, cfop, unidadeComercial, quantidadeComercial, valorUnitario, valorTotalBruto, codigoDeBarrasTributavel, unidadeTributavel, quantidadeTributavel, valorUnitarioTributavel, valorFrete, valorSeguro, valorDesconto, valorOutrasDespesasAcessorias, compoeValorNota, numeroPedidoCliente, numeroPedidoItemCliente, numeroControleFCI, veiculo, combustivel, numeroRECOPI,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1001, 'codigo_1', 'codigoDeBarras_1', 'descricao_1', 'ncm_1', 'codigoEspecificadorSituacaoTributaria_1', 'extipi_1', 'cfop_1', 'unidadeComercial_1', 'quantidadeComercial_1', 'valorUnitario_1', 'valorTotalBruto_1', 'codigoDeBarrasTributavel_1', 'unidadeTributavel_1', 'quantidadeTributavel_1', 'valorUnitarioTributavel_1', 'valorFrete_1', 'valorSeguro_1', 'valorDesconto_1', 'valorOutrasDespesasAcessorias_1', 1001, 'numeroPedidoCliente_1', 1001, 'numeroControleFCI_1', 1001, 1001, 'numeroRECOPI_1',10000,1,1,1,'system',1480868161253,'rod',1480868161253);

INSERT INTO NFNotaInfoItemProduto( id, codigo, codigoDeBarras, descricao, ncm, codigoEspecificadorSituacaoTributaria, extipi, cfop, unidadeComercial, quantidadeComercial, valorUnitario, valorTotalBruto, codigoDeBarrasTributavel, unidadeTributavel, quantidadeTributavel, valorUnitarioTributavel, valorFrete, valorSeguro, valorDesconto, valorOutrasDespesasAcessorias, compoeValorNota, numeroPedidoCliente, numeroPedidoItemCliente, numeroControleFCI, veiculo, combustivel, numeroRECOPI,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1002, 'codigo_2', 'codigoDeBarras_2', 'descricao_2', 'ncm_2', 'codigoEspecificadorSituacaoTributaria_2', 'extipi_2', 'cfop_2', 'unidadeComercial_2', 'quantidadeComercial_2', 'valorUnitario_2', 'valorTotalBruto_2', 'codigoDeBarrasTributavel_2', 'unidadeTributavel_2', 'quantidadeTributavel_2', 'valorUnitarioTributavel_2', 'valorFrete_2', 'valorSeguro_2', 'valorDesconto_2', 'valorOutrasDespesasAcessorias_2', 1002, 'numeroPedidoCliente_2', 1002, 'numeroControleFCI_2', 1002, 1002, 'numeroRECOPI_2',10000,1,1,1,'system',1480868161253,'rod',1480868161253);
