
INSERT INTO NFNotaInfoItemImpostoICMSSN201( id, origem, situacaoOperacaoSN, modalidadeBCICMSST, percentualMargemValorAdicionadoICMSST, percentualReducaoBCICMSST, valorBCICMSST, percentualAliquotaImpostoICMSST, valorICMSST, percentualAliquotaAplicavelCalculoCreditoSN, valorCreditoICMSSN,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1000, 1000, 1000, 1000, 'percentualMargemValorAdicionadoICMSST_0', 'percentualReducaoBCICMSST_0', 'valorBCICMSST_0', 'percentualAliquotaImpostoICMSST_0', 'valorICMSST_0', 'percentualAliquotaAplicavelCalculoCreditoSN_0', 'valorCreditoICMSSN_0',10000,1,1,1,'system',1480868161265,'rod',1480868161265);

INSERT INTO NFNotaInfoItemImpostoICMSSN201( id, origem, situacaoOperacaoSN, modalidadeBCICMSST, percentualMargemValorAdicionadoICMSST, percentualReducaoBCICMSST, valorBCICMSST, percentualAliquotaImpostoICMSST, valorICMSST, percentualAliquotaAplicavelCalculoCreditoSN, valorCreditoICMSSN,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1001, 1001, 1001, 1001, 'percentualMargemValorAdicionadoICMSST_1', 'percentualReducaoBCICMSST_1', 'valorBCICMSST_1', 'percentualAliquotaImpostoICMSST_1', 'valorICMSST_1', 'percentualAliquotaAplicavelCalculoCreditoSN_1', 'valorCreditoICMSSN_1',10000,1,1,1,'system',1480868161265,'rod',1480868161265);

INSERT INTO NFNotaInfoItemImpostoICMSSN201( id, origem, situacaoOperacaoSN, modalidadeBCICMSST, percentualMargemValorAdicionadoICMSST, percentualReducaoBCICMSST, valorBCICMSST, percentualAliquotaImpostoICMSST, valorICMSST, percentualAliquotaAplicavelCalculoCreditoSN, valorCreditoICMSSN,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1002, 1002, 1002, 1002, 'percentualMargemValorAdicionadoICMSST_2', 'percentualReducaoBCICMSST_2', 'valorBCICMSST_2', 'percentualAliquotaImpostoICMSST_2', 'valorICMSST_2', 'percentualAliquotaAplicavelCalculoCreditoSN_2', 'valorCreditoICMSSN_2',10000,1,1,1,'system',1480868161265,'rod',1480868161265);
