
INSERT INTO NFNotaInfoItemImpostoICMS10( id, origem, situacaoTributaria, modalidadeBCICMS, valorBaseCalculo, percentualAliquota, valorTributo, modalidadeBCICMSST, percentualMargemValorICMSST, percentualReducaoBCICMSST, valorBCICMSST, percentualAliquotaImpostoICMSST, valorICMSST,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1000, 1000, 1000, 1000, 'valorBaseCalculo_0', 'percentualAliquota_0', 'valorTributo_0', 1000, 'percentualMargemValorICMSST_0', 'percentualReducaoBCICMSST_0', 'valorBCICMSST_0', 'percentualAliquotaImpostoICMSST_0', 'valorICMSST_0',10000,1,1,1,'system',1480868161259,'rod',1480868161259);

INSERT INTO NFNotaInfoItemImpostoICMS10( id, origem, situacaoTributaria, modalidadeBCICMS, valorBaseCalculo, percentualAliquota, valorTributo, modalidadeBCICMSST, percentualMargemValorICMSST, percentualReducaoBCICMSST, valorBCICMSST, percentualAliquotaImpostoICMSST, valorICMSST,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1001, 1001, 1001, 1001, 'valorBaseCalculo_1', 'percentualAliquota_1', 'valorTributo_1', 1001, 'percentualMargemValorICMSST_1', 'percentualReducaoBCICMSST_1', 'valorBCICMSST_1', 'percentualAliquotaImpostoICMSST_1', 'valorICMSST_1',10000,1,1,1,'system',1480868161259,'rod',1480868161259);

INSERT INTO NFNotaInfoItemImpostoICMS10( id, origem, situacaoTributaria, modalidadeBCICMS, valorBaseCalculo, percentualAliquota, valorTributo, modalidadeBCICMSST, percentualMargemValorICMSST, percentualReducaoBCICMSST, valorBCICMSST, percentualAliquotaImpostoICMSST, valorICMSST,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1002, 1002, 1002, 1002, 'valorBaseCalculo_2', 'percentualAliquota_2', 'valorTributo_2', 1002, 'percentualMargemValorICMSST_2', 'percentualReducaoBCICMSST_2', 'valorBCICMSST_2', 'percentualAliquotaImpostoICMSST_2', 'valorICMSST_2',10000,1,1,1,'system',1480868161260,'rod',1480868161260);
