
INSERT INTO NFNotaInfoItemImpostoICMSSN900( id, origem, situacaoOperacaoSN, modalidadeBCICMS, valorBCICMS, percentualReducaoBC, percentualAliquotaImposto, valorICMS, modalidadeBCICMSST, percentualMargemValorAdicionadoICMSST, percentualReducaoBCICMSST, valorBCICMSST, percentualAliquotaImpostoICMSST, valorICMSST, percentualAliquotaAplicavelCalculoCreditoSN,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1000, 'origem_0', 'situacaoOperacaoSN_0', 'modalidadeBCICMS_0', 'valorBCICMS_0', 'percentualReducaoBC_0', 'percentualAliquotaImposto_0', 'valorICMS_0', 'modalidadeBCICMSST_0', 'percentualMargemValorAdicionadoICMSST_0', 'percentualReducaoBCICMSST_0', 'valorBCICMSST_0', 'percentualAliquotaImpostoICMSST_0', 'valorICMSST_0', 'percentualAliquotaAplicavelCalculoCreditoSN_0',10000,1,1,1,'system',1480868161266,'rod',1480868161266);

INSERT INTO NFNotaInfoItemImpostoICMSSN900( id, origem, situacaoOperacaoSN, modalidadeBCICMS, valorBCICMS, percentualReducaoBC, percentualAliquotaImposto, valorICMS, modalidadeBCICMSST, percentualMargemValorAdicionadoICMSST, percentualReducaoBCICMSST, valorBCICMSST, percentualAliquotaImpostoICMSST, valorICMSST, percentualAliquotaAplicavelCalculoCreditoSN,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1001, 'origem_1', 'situacaoOperacaoSN_1', 'modalidadeBCICMS_1', 'valorBCICMS_1', 'percentualReducaoBC_1', 'percentualAliquotaImposto_1', 'valorICMS_1', 'modalidadeBCICMSST_1', 'percentualMargemValorAdicionadoICMSST_1', 'percentualReducaoBCICMSST_1', 'valorBCICMSST_1', 'percentualAliquotaImpostoICMSST_1', 'valorICMSST_1', 'percentualAliquotaAplicavelCalculoCreditoSN_1',10000,1,1,1,'system',1480868161266,'rod',1480868161266);

INSERT INTO NFNotaInfoItemImpostoICMSSN900( id, origem, situacaoOperacaoSN, modalidadeBCICMS, valorBCICMS, percentualReducaoBC, percentualAliquotaImposto, valorICMS, modalidadeBCICMSST, percentualMargemValorAdicionadoICMSST, percentualReducaoBCICMSST, valorBCICMSST, percentualAliquotaImpostoICMSST, valorICMSST, percentualAliquotaAplicavelCalculoCreditoSN,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1002, 'origem_2', 'situacaoOperacaoSN_2', 'modalidadeBCICMS_2', 'valorBCICMS_2', 'percentualReducaoBC_2', 'percentualAliquotaImposto_2', 'valorICMS_2', 'modalidadeBCICMSST_2', 'percentualMargemValorAdicionadoICMSST_2', 'percentualReducaoBCICMSST_2', 'valorBCICMSST_2', 'percentualAliquotaImpostoICMSST_2', 'valorICMSST_2', 'percentualAliquotaAplicavelCalculoCreditoSN_2',10000,1,1,1,'system',1480868161266,'rod',1480868161266);
