
INSERT INTO NFNotaInfoICMSTotal( id, baseCalculoICMS, valorTotalICMS, valorICMSDesonerado, valorICMSFundoCombatePobreza, valorICMSPartilhaDestinatario, valorICMSPartilhaRementente, baseCalculoICMSST, valorTotalICMSST, valorTotalDosProdutosServicos, valorTotalFrete, valorTotalSeguro, valorTotalDesconto, valorTotalII, valorTotalIPI, valorPIS, valorCOFINS, outrasDespesasAcessorias, valorTotalNFe, valorTotalTributos,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1000, 'baseCalculoICMS_0', 'valorTotalICMS_0', 'valorICMSDesonerado_0', 'valorICMSFundoCombatePobreza_0', 'valorICMSPartilhaDestinatario_0', 'valorICMSPartilhaRementente_0', 'baseCalculoICMSST_0', 'valorTotalICMSST_0', 'valorTotalDosProdutosServicos_0', 'valorTotalFrete_0', 'valorTotalSeguro_0', 'valorTotalDesconto_0', 'valorTotalII_0', 'valorTotalIPI_0', 'valorPIS_0', 'valorCOFINS_0', 'outrasDespesasAcessorias_0', 'valorTotalNFe_0', 'valorTotalTributos_0',10000,1,1,1,'system',1475163820865,'rod',1475163820865);

INSERT INTO NFNotaInfoICMSTotal( id, baseCalculoICMS, valorTotalICMS, valorICMSDesonerado, valorICMSFundoCombatePobreza, valorICMSPartilhaDestinatario, valorICMSPartilhaRementente, baseCalculoICMSST, valorTotalICMSST, valorTotalDosProdutosServicos, valorTotalFrete, valorTotalSeguro, valorTotalDesconto, valorTotalII, valorTotalIPI, valorPIS, valorCOFINS, outrasDespesasAcessorias, valorTotalNFe, valorTotalTributos,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1001, 'baseCalculoICMS_1', 'valorTotalICMS_1', 'valorICMSDesonerado_1', 'valorICMSFundoCombatePobreza_1', 'valorICMSPartilhaDestinatario_1', 'valorICMSPartilhaRementente_1', 'baseCalculoICMSST_1', 'valorTotalICMSST_1', 'valorTotalDosProdutosServicos_1', 'valorTotalFrete_1', 'valorTotalSeguro_1', 'valorTotalDesconto_1', 'valorTotalII_1', 'valorTotalIPI_1', 'valorPIS_1', 'valorCOFINS_1', 'outrasDespesasAcessorias_1', 'valorTotalNFe_1', 'valorTotalTributos_1',10000,1,1,1,'system',1475163820865,'rod',1475163820865);

INSERT INTO NFNotaInfoICMSTotal( id, baseCalculoICMS, valorTotalICMS, valorICMSDesonerado, valorICMSFundoCombatePobreza, valorICMSPartilhaDestinatario, valorICMSPartilhaRementente, baseCalculoICMSST, valorTotalICMSST, valorTotalDosProdutosServicos, valorTotalFrete, valorTotalSeguro, valorTotalDesconto, valorTotalII, valorTotalIPI, valorPIS, valorCOFINS, outrasDespesasAcessorias, valorTotalNFe, valorTotalTributos,parentId,tabelaEnumValue,emprId,processId,create_user,create_date,modify_user,modify_date)values
( 1002, 'baseCalculoICMS_2', 'valorTotalICMS_2', 'valorICMSDesonerado_2', 'valorICMSFundoCombatePobreza_2', 'valorICMSPartilhaDestinatario_2', 'valorICMSPartilhaRementente_2', 'baseCalculoICMSST_2', 'valorTotalICMSST_2', 'valorTotalDosProdutosServicos_2', 'valorTotalFrete_2', 'valorTotalSeguro_2', 'valorTotalDesconto_2', 'valorTotalII_2', 'valorTotalIPI_2', 'valorPIS_2', 'valorCOFINS_2', 'outrasDespesasAcessorias_2', 'valorTotalNFe_2', 'valorTotalTributos_2',10000,1,1,1,'system',1475163820865,'rod',1475163820865);
