unit Unit1;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls, BrvCustomEdit, BrvEdit, ComCtrls, ExtCtrls, Buttons, BrvBitBtn;

type
  TForm1 = class(TForm)
    Panel1: TPanel;
    Panel2: TPanel;
    PgcFundo: TPageControl;
    TbsFiltro: TTabSheet;
    TbsConsulta: TTabSheet;
    FileOpenDialog1: TFileOpenDialog;
    BrvEdit1: TBrvEdit;
    GroupBox1: TGroupBox;
    TabSheet1: TTabSheet;
    TabSheet2: TTabSheet;
    TabSheet3: TTabSheet;
    TabSheet4: TTabSheet;
    TabSheet5: TTabSheet;
    SpeedButton1: TSpeedButton;
    Memo1: TMemo;
    CheckBox1: TCheckBox;
    CheckBox2: TCheckBox;
    CheckBox3: TCheckBox;
    CheckBox4: TCheckBox;
    CheckBox5: TCheckBox;
    CheckBox6: TCheckBox;
    CheckBox7: TCheckBox;
    CheckBox8: TCheckBox;
    CheckBox9: TCheckBox;
    CheckBox10: TCheckBox;
    CheckBox11: TCheckBox;
    Edit1: TEdit;
    Label1: TLabel;
    Label2: TLabel;
    BtnPesquisa: TBrvBitBtn;
    GroupBox2: TGroupBox;
    CheckBox13: TCheckBox;
    Memo2: TMemo;
    CheckBox14: TCheckBox;
    CheckBox15: TCheckBox;
    CheckBox16: TCheckBox;
    CheckBox17: TCheckBox;
    CheckBox18: TCheckBox;
    CheckBox19: TCheckBox;
    Memo3: TMemo;
    Memo4: TMemo;
    Memo5: TMemo;
    Memo6: TMemo;
    Memo7: TMemo;
    TabSheet6: TTabSheet;
    TabSheet7: TTabSheet;
    TabSheet8: TTabSheet;
    TabSheet9: TTabSheet;
    Memo8: TMemo;
    Memo9: TMemo;
    Memo10: TMemo;
    Memo11: TMemo;
    GroupBox3: TGroupBox;
    CheckBox12: TCheckBox;
    CheckBox20: TCheckBox;
    CheckBox21: TCheckBox;
    CheckBox22: TCheckBox;
    CheckBox23: TCheckBox;
    CheckBox24: TCheckBox;
    GroupBox4: TGroupBox;
    CheckBox25: TCheckBox;
    CheckBox26: TCheckBox;
    procedure SpeedButton1Click(Sender: TObject);
    procedure BtnPesquisaClick(Sender: TObject);
  private
    { Private declarations }
  public
    procedure gerarModelo(Txt:String);
    function escreverCode(Txt:String):String;
    function verificadorCode(Txt:String):String;
    function criarCodeInquiryResponse(Txt:String):String;
    function criarCodeInquiryRequest(Txt:String):String;
    function criarCodeResponse(Txt:String):String;
    function criarCodeRequest(Txt:String):String;
    Function Explode(Texto, Separador : String) : String;
    Function PrimeiraMaiscula(Texto: String) : String;
    Function MostrarMemo(Memo: TMemo) : String;
    function criarCodeIClasseBCF(Txt:String):String;
    function criarCodeClasseBCFImpl(Txt:String):String;
    function criarCodeIClasseBCL(Txt:String):String;
    function criarCodeIClasseBCLImpl(Txt:String):String;
    function criarCodeIClasseDAC(Txt:String):String;
    function criarCodeIClasseDACImpl(Txt:String):String;
    function criarCodeClasseXML(Txt:String):String;
    function criarCodeClasseSqlMapConfigXml(Txt:String):String;
    function criarCodeClasseAPIControler(Txt:String):String;
  end;

var
  Form1: TForm1;
  arq: TextFile;
  F:TextFile;

implementation

{$R *.dfm}
function TForm1.criarCodeClasseAPIControler(Txt:String):String;
begin
      AssignFile(F,'c:\I'+PrimeiraMaiscula(Edit1.Text)+'DAC.java');
      Writeln(F,'package com.sensus.mlc.wui.almoxarifado;');
      Writeln(F,'import javax.servlet.http.HttpServletRequest;');
      Writeln(F,'');
      Writeln(F,'import org.slf4j.Logger;');
      Writeln(F,'import org.slf4j.LoggerFactory;');
      Writeln(F,'import org.springframework.stereotype.Controller;');
      Writeln(F,'import org.springframework.web.bind.annotation.RequestBody;');
      Writeln(F,'import org.springframework.web.bind.annotation.RequestMapping;');
      Writeln(F,'import org.springframework.web.bind.annotation.RequestMethod;');
      Writeln(F,'import org.springframework.web.bind.annotation.ResponseBody;');
      Writeln(F,'');
      Writeln(F,'import com.sensus.common.model.response.Response;');
      Writeln(F,'import com.sensus.common.util.SensusInterfaceUtil;');
      Writeln(F,'import com.sensus.mlc.almoxarifado.bcf.IAlmoxarifadoBCF;');
      Writeln(F,'import com.sensus.mlc.almoxarifado.model.request.AlmoxarifadoRequest;');
      Writeln(F,'import com.sensus.mlc.almoxarifado.model.request.InquiryAlmoxarifadoRequest;');
      Writeln(F,'import com.sensus.mlc.almoxarifado.model.response.AlmoxarifadoResponse;');
      Writeln(F,'import com.sensus.mlc.almoxarifado.model.response.InquiryAlmoxarifadoResponse;');
      Writeln(F,'import com.sensus.mlc.wui.BaseController;');
      Writeln(F,'import com.sensus.mlc.wui.light.LightAPIController;');
      Writeln(F,'');
      Writeln(F,'/** ');
      Writeln(F,'* @author QATEmployee ');
      Writeln(F,'* ');
      Writeln(F,'*/ ');
      Writeln(F,'@Controller');
      Writeln(F,'@RequestMapping("/api/almoxarifado") ');
      Writeln(F,'public class AlmoxarifadoAPIController extends BaseController  ');
      Writeln(F,'{ ');
      Writeln(F,'');
      Writeln(F,'/* ');
      Writeln(F,'* URLs Mapping   ');
      Writeln(F,'*/  ');
      Writeln(F,'/** The Constant MAP_FETCH. */ ');
      Writeln(F,'private static final String MAP_FETCH = "/fetch";');
      Writeln(F,'');
      Writeln(F,'private static final String MAP_FETCHALL = "/fetchall";');
      Writeln(F,'');
      Writeln(F,'/** The Constant MAP_DELETE. */ ');
      Writeln(F,'private static final String MAP_DELETE = "/delete";');
      Writeln(F,'');
      Writeln(F,'/** The Constant MAP_INSERT. */  ');
      Writeln(F,'private static final String MAP_INSERT = "/insert";');
      Writeln(F,'');
      Writeln(F,'/** The Constant MAP_INSERT. */  ');
      Writeln(F,'private static final String MAP_UPDATE = "/update";');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'private IAlmoxarifadoBCF almoxarifadoBCF;');
      Writeln(F,'');
      Writeln(F,'/** The Constant LOG. */');
      Writeln(F,'private static final Logger LOG = LoggerFactory.getLogger(LightAPIController.class);');
      Writeln(F,'');
      Writeln(F,'/** The Constant CONTROLLER_EXCEPTION_MSG. */  ');
      Writeln(F,'public static final String CONTROLLER_EXCEPTION_MSG = "TagAPIController";');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'public IAlmoxarifadoBCF getAlmoxarifadoBCF() { ');
      Writeln(F,'return almoxarifadoBCF;');
      Writeln(F,'}  ');
      Writeln(F,'');
      Writeln(F,'public void setAlmoxarifadoBCF(IAlmoxarifadoBCF almoxarifadoBCF) {  ');
      Writeln(F,'this.almoxarifadoBCF = almoxarifadoBCF;');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'@RequestMapping(value = MAP_INSERT, method = RequestMethod.POST) ');
      Writeln(F,'@ResponseBody   ');
      Writeln(F,'public Response insert(@RequestBody AlmoxarifadoRequest almoxarifadoRequest, HttpServletRequest request) ');
      Writeln(F,'{ ');
      Writeln(F,'');
      Writeln(F,'AlmoxarifadoResponse response = new AlmoxarifadoResponse();');
      Writeln(F,'try  ');
      Writeln(F,'{ ');
      Writeln(F,'setUserContext(almoxarifadoRequest, request);');
      Writeln(F,'');
      Writeln(F,'response = getAlmoxarifadoBCF().insertAlmoxarifado(almoxarifadoRequest);');
      Writeln(F,'');
      Writeln(F,'}  ');
      Writeln(F,'catch (Exception e)');
      Writeln(F,'{   ');
      Writeln(F,'SensusInterfaceUtil.handleException(LOG, response, e, DEFAULT_EXCEPTION_MSG,  ');
      Writeln(F,'			new String[] {CONTROLLER_EXCEPTION_MSG});');
      Writeln(F,'}  ');
      Writeln(F,'return response;');
      Writeln(F,'');
      Writeln(F,'} ');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'/**  ');
      Writeln(F,'* Update filial.  ');
      Writeln(F,'*    ');
      Writeln(F,'* @param filialRequest the filial request  ');
      Writeln(F,'* @return the filial response  ');
      Writeln(F,'*/  ');
      Writeln(F,'');
      Writeln(F,'@RequestMapping(value = MAP_UPDATE, method = RequestMethod.POST)  ');
      Writeln(F,'@ResponseBody  ');
      Writeln(F,'public Response updateAlmoxarifado(@RequestBody AlmoxarifadoRequest almoxarifadoRequest, HttpServletRequest request) ');
      Writeln(F,'{ ');
      Writeln(F,'');
      Writeln(F,'AlmoxarifadoResponse response = new AlmoxarifadoResponse();');
      Writeln(F,'try  ');
      Writeln(F,'{ ');
      Writeln(F,'setUserContext(almoxarifadoRequest, request);');
      Writeln(F,'');
      Writeln(F,'response = getAlmoxarifadoBCF().updateAlmoxarifado(almoxarifadoRequest);');
      Writeln(F,'');
      Writeln(F,'} ');
      Writeln(F,'catch (Exception e) ');
      Writeln(F,'{  ');
      Writeln(F,'SensusInterfaceUtil.handleException(LOG, response, e, DEFAULT_EXCEPTION_MSG,  ');
      Writeln(F,'			new String[] {CONTROLLER_EXCEPTION_MSG});');
      Writeln(F,'}  ');
      Writeln(F,'return response;');
      Writeln(F,'');
      Writeln(F,'}  ');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'/**  ');
      Writeln(F,'* Delete filial. ');
      Writeln(F,'*      ');
      Writeln(F,'* @param filialRequest the filial request ');
      Writeln(F,'* @return the filial response    ');
      Writeln(F,'*/      ');
      Writeln(F,'');
      Writeln(F,'@RequestMapping(value = MAP_DELETE, method = RequestMethod.POST)  ');
      Writeln(F,'@ResponseBody  ');
      Writeln(F,'public Response deleteAlmoxarifado(@RequestBody AlmoxarifadoRequest almoxarifadoRequest, HttpServletRequest request) ');
      Writeln(F,'{  ');
      Writeln(F,'');
      Writeln(F,'AlmoxarifadoResponse response = new AlmoxarifadoResponse();');
      Writeln(F,'try ');
      Writeln(F,'{ ');
      Writeln(F,'setUserContext(almoxarifadoRequest, request);');
      Writeln(F,'');
      Writeln(F,'response = getAlmoxarifadoBCF().deleteAlmoxarifado(almoxarifadoRequest);');
      Writeln(F,'');
      Writeln(F,'} ');
      Writeln(F,'catch (Exception e) ');
      Writeln(F,'{ ');
      Writeln(F,'SensusInterfaceUtil.handleException(LOG, response, e, DEFAULT_EXCEPTION_MSG,');
      Writeln(F,'			new String[] {CONTROLLER_EXCEPTION_MSG});');
      Writeln(F,'}');
      Writeln(F,'return response;');
      Writeln(F,'');
      Writeln(F,'}  ');
      Writeln(F,'');
      Writeln(F,'/** ');
      Writeln(F,'* Fetch all filial.  ');
      Writeln(F,'*  ');
      Writeln(F,'* @param inquiryfilialRequest the inquiryfilial request  ');
      Writeln(F,'* @return the inquiry filial response  ');
      Writeln(F,'*/ ');
      Writeln(F,'');
      Writeln(F,'@RequestMapping(value = MAP_FETCHALL, method = RequestMethod.POST) ');
      Writeln(F,'@ResponseBody ');
      Writeln(F,'public Response fetch(@RequestBody InquiryAlmoxarifadoRequest inquiryAlmoxarifadoRequest, HttpServletRequest request) ');
      Writeln(F,'{  ');
      Writeln(F,'');
      Writeln(F,'InquiryAlmoxarifadoResponse response = new InquiryAlmoxarifadoResponse();');
      Writeln(F,'try');
      Writeln(F,'{ ');
      Writeln(F,'setUserContext(inquiryAlmoxarifadoRequest, request);');
      Writeln(F,'');
      Writeln(F,'response = getAlmoxarifadoBCF().fetchAllAlmoxarifado(inquiryAlmoxarifadoRequest);');
      Writeln(F,'');
      Writeln(F,'}');
      Writeln(F,'catch (Exception e) ');
      Writeln(F,'{   ');
      Writeln(F,'SensusInterfaceUtil.handleException(LOG, response, e, DEFAULT_EXCEPTION_MSG,  ');
      Writeln(F,'			new String[] {CONTROLLER_EXCEPTION_MSG});');
      Writeln(F,'} ');
      Writeln(F,'return response;');
      Writeln(F,'');
      Writeln(F,'} ');
      Writeln(F,'');
      Writeln(F,'/**  ');
      Writeln(F,'* Fetch filial by id. ');
      Writeln(F,'* ');
      Writeln(F,'* @param filialRequest the filial request   ');
      Writeln(F,'* @return the filial response   ');
      Writeln(F,'*/    ');
      Writeln(F,'');
      Writeln(F,'@RequestMapping(value = MAP_FETCH, method = RequestMethod.POST) ');
      Writeln(F,'@ResponseBody ');
      Writeln(F,'public Response fetch(@RequestBody AlmoxarifadoRequest almoxarifadoRequest, HttpServletRequest request)   ');
      Writeln(F,'{ ');
      Writeln(F,'');
      Writeln(F,'AlmoxarifadoResponse response = new AlmoxarifadoResponse();');
      Writeln(F,'try   ');
      Writeln(F,'{  ');
      Writeln(F,'setUserContext(almoxarifadoRequest, request);');
      Writeln(F,'');
      Writeln(F,'response = getAlmoxarifadoBCF().fetchAlmoxarifadoById(almoxarifadoRequest);');
      Writeln(F,'');
      Writeln(F,'} ');
      Writeln(F,'catch (Exception e)');
      Writeln(F,'{');
      Writeln(F,'SensusInterfaceUtil.handleException(LOG, response, e, DEFAULT_EXCEPTION_MSG,  ');
      Writeln(F,'			new String[] {CONTROLLER_EXCEPTION_MSG});');
      Writeln(F,'} ');
      Writeln(F,'return response;');
      Writeln(F,'');
      Writeln(F,'} ');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'}  ');
      Closefile(F);
end;

function TForm1.criarCodeClasseSqlMapConfigXml(Txt:String):String;
begin
      AssignFile(F,'c:\I'+PrimeiraMaiscula(Edit1.Text)+'DAC.java');
      Writeln(F,'<?xml version="1.0" encoding="UTF-8"?>');
      Writeln(F,'<!DOCTYPE configuration');
      Writeln(F,'PUBLIC "-//mybatis.org//DTD Config 3.0//EN"');
      Writeln(F,'"http://mybatis.org/dtd/mybatis-3-config.dtd">');

      Writeln(F,'<configuration>');

      Writeln(F,'<settings>');
      Writeln(F,'<setting name="lazyLoadingEnabled" value="false" />');
      Writeln(F,'</settings>');

      Writeln(F,'<typeAliases>');
      Writeln(F,'<!-- Empresa mapping -->');
      Writeln(F,'<typeAlias alias="InquiryEmpresaRequest" 	type="com.sensus.mlc.empresa.model.request.InquiryEmpresaRequest" />');
      Writeln(F,'<typeAlias alias="EmpresaRequest" 			type="com.sensus.mlc.empresa.model.request.EmpresaRequest" />');
      Writeln(F,'<typeAlias alias="FilialRequest" 		type="com.sensus.mlc.filial.model.request.FilialRequest" />');
      Writeln(F,'<typeAlias alias="EnderecoRequest" 		type="com.sensus.mlc.endereco.model.request.EnderecoRequest" />');

      Writeln(F,'<!-- Empresa and Smartpoint joint mapping -->');
      Writeln(F,'<typeAlias alias="Empresa"  Writeln(F,''type="com.sensus.mlc.empresa.model.Empresa"/>');
      Writeln(F,'<typeAlias alias="Filial" Writeln(F,''    type="com.sensus.mlc.filial.model.Filial"/>');
      Writeln(F,'<typeAlias alias="Endereco" Writeln(F,''type="com.sensus.mlc.endereco.model.Endereco"/>');

      Writeln(F,'<!-- Smartpoint mapping -->');
      Writeln(F,'<typeAlias alias="Group" Writeln(F,''		  type="com.sensus.mlc.group.model.Group" />');
      Writeln(F,'<typeAlias alias="Tag" Writeln(F,''	      type="com.sensus.mlc.tag.model.Tag" />');
      Writeln(F,'<typeAlias alias="StatusMessage" Writeln(F,''  type="com.sensus.mlc.smartpoint.model.StatusMessage" />');
      Writeln(F,'<typeAlias alias="LightParameter" Writeln(F,''  type="com.sensus.mlc.smartpoint.model.LightParameter" />');
      Writeln(F,'<typeAlias alias="PropertyValidValue" 			  type="com.sensus.mlc.smartpoint.model.PropertyValidValue" />');
      Writeln(F,'<typeAlias alias="StatusException" Writeln(F,''  type="com.sensus.mlc.smartpoint.model.StatusException" />');
      Writeln(F,'<typeAlias alias="LightRequest" Writeln(F,''  type="com.sensus.mlc.smartpoint.model.request.LightRequest" />');
      Writeln(F,'<typeAlias alias="EventSchedule" Writeln(F,''  type="com.sensus.mlc.schedule.model.EventSchedule" />');
      Writeln(F,'<typeAlias alias="OffsetSchedule" Writeln(F,''  type="com.sensus.mlc.schedule.model.OffsetSchedule" />');
      Writeln(F,'<typeAlias alias="CustomSearch" Writeln(F,''  type="com.sensus.mlc.smartpoint.model.CustomSearch" />');
      Writeln(F,'<typeAlias alias="SearchParameter" Writeln(F,''  type="com.sensus.mlc.smartpoint.model.SearchParameter" />');
      Writeln(F,'<typeAlias alias="TimeZoneInfo" Writeln(F,''  type="com.sensus.mlc.base.model.TimeZoneInfo" />');
      Writeln(F,'<typeAlias alias="SensusPartNumberConfiguration"  type="com.sensus.mlc.smartpoint.model.SensusPartNumberConfiguration" />');
      Writeln(F,'<typeAlias alias="LightHistory" Writeln(F,''  type="com.sensus.mlc.smartpoint.model.LightHistory" />');
      Writeln(F,'<typeAlias alias="Schedule" Writeln(F,''	  type="com.sensus.mlc.schedule.model.Schedule" />');
      Writeln(F,'<typeAlias alias="Column" Writeln(F,''		  type="com.sensus.mlc.smartpoint.model.Column" />');
      Writeln(F,'<typeAlias alias="GuaranteeLightExistenceRequest" type="com.sensus.mlc.smartpoint.model.request.GuaranteeLightExistenceRequest" />');
      Writeln(F,'<typeAlias alias="CurrentAlarmWarningMessage" 	  type="com.sensus.mlc.smartpoint.model.CurrentAlarmWarningMessage" />');
      Writeln(F,'<typeAlias alias="CustomSearchRequest" 			  type="com.sensus.mlc.smartpoint.model.request.CustomSearchRequest" />');
      Writeln(F,'<typeAlias alias="TenantRequest" Writeln(F,''  type="com.sensus.mlc.tenant.model.request.TenantRequest" />');
      Writeln(F,'<typeAlias alias="LightStatusRequest" 			  type="com.sensus.mlc.smartpoint.model.request.LightStatusRequest" />');
      Writeln(F,'<typeAlias alias="LightingControlRequest" 		  type="com.sensus.mlc.base.model.request.LightingControlRequest" />');
      Writeln(F,'<typeAlias alias="ScheduleRequest" Writeln(F,''  type="com.sensus.mlc.schedule.model.request.ScheduleRequest" />');
      Writeln(F,'<typeAlias alias="PropertyValidValuesRequest" 	  type="com.sensus.mlc.smartpoint.model.request.PropertyValidValuesRequest" />');
      Writeln(F,'<typeAlias alias="ColumnFilterRequest" 			  type="com.sensus.mlc.smartpoint.model.request.ColumnFilterRequest" />');
      Writeln(F,'<typeAlias alias="ColumnFilterResponse" 		  type="com.sensus.mlc.smartpoint.model.response.ColumnFilterResponse" />');

      Writeln(F,'</typeAliases>');

      Writeln(F,'<mappers>');
      Writeln(F,'<mapper resource="com/sensus/mlc/empresa/dac/mybatis/map/Empresa.xml"/>');
      Writeln(F,'<mapper resource="com/sensus/mlc/filial/dac/mybatis/map/Filial.xml" />');
      Writeln(F,'<mapper resource="com/sensus/mlc/endereco/dac/mybatis/map/Endereco.xml" />');
      Writeln(F,'</mappers>');

      Writeln(F,'</configuration>');


      Closefile(F);
end;
function TForm1.criarCodeClasseXML(Txt:String):String;
begin
      AssignFile(F,'c:\I'+PrimeiraMaiscula(Edit1.Text)+'DAC.java');
      Writeln(F,'<?xml version="1.0" encoding="UTF-8"?>');
      Writeln(F,'<!DOCTYPE mapper ');
      Writeln(F,'PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" ');
      Writeln(F,'"http://mybatis.org/dtd/mybatis-3-mapper.dtd">');

      Writeln(F,'<mapper namespace="Empresa">');

      Writeln(F,'<resultMap id="EmpresasResult" type="Empresa">');
      Writeln(F,'<result property="codemp" column="codemp" />');
      Writeln(F,'<result property="razemp" column="razemp" />');
      Writeln(F,'<result property="nomeemp" column="nomeemp" />');
      Writeln(F,'<result property="cnpjemp" column="cnpjemp" />');
      Writeln(F,'<result property="inscemp" column="inscemp" />');
      Writeln(F,'<result property="endemp" column="endemp" />');
      Writeln(F,'<result property="numemp" column="numemp" />');
      Writeln(F,'<result property="complemp" column="complemp" />');
      Writeln(F,'<result property="bairemp" column="bairemp" />');
      Writeln(F,'<result property="cepemp" column="cepemp" />');
      Writeln(F,'<result property="cidemp" column="cidemp" />');
      Writeln(F,'<result property="ufemp" column="ufemp" />');
      Writeln(F,'<result property="dddemp" column="dddemp" />');
      Writeln(F,'<result property="foneemp" column="foneemp" />');
      Writeln(F,'<result property="faxemp" column="faxemp" />');
      Writeln(F,'<result property="emailemp" column="emailemp" />');
      Writeln(F,'<result property="wwwemp" column="wwwemp" />');
      Writeln(F,'<result property="codeanemp" column="codeanemp" />');
      Writeln(F,'<result property="nomecontemp" column="nomecontemp" />');
      Writeln(F,'<result property="multialmoxemp" column="multialmoxemp" />');
      Writeln(F,'<result property="fotoemp" column="fotoemp" />');
      Writeln(F,'<result property="codmunic" column="codmunic" />');
      Writeln(F,'<result property="siglauf" column="siglauf" />');
      Writeln(F,'<result property="codpais" column="codpais" />');
      Writeln(F,'<result property="percissemp" column="percissemp" />');
      Writeln(F,'<result property="codpaisemp" column="codpaisemp" />');
      Writeln(F,'<result property="dtins" column="dtins" />');
      Writeln(F,'<result property="hins" column="hins" />');
      Writeln(F,'<result property="idusuins" column="idusuins" />');
      Writeln(F,'<result property="dtalt" column="dtalt" />');
      Writeln(F,'<result property="halt" column="halt" />');
      Writeln(F,'<result property="idusualt" column="idusualt" />');
      Writeln(F,'<collection property="listFilial" column="codemp" ');
      Writeln(F,'select="Empresa.fetchAllFiliaisById" />');
      Writeln(F,'<collection property="codend" column="codend" ');
      Writeln(F,'select="Empresa.fetchAllEnderecoByEmpresa" />');
      Writeln(F,'</resultMap>');

      Writeln(F,'<resultMap id="FilialResult" type="Filial">');
      Writeln(F,'<result property="codemp" column="codemp" />');
      Writeln(F,'<result property="codfilial" column="codfilial" />');
      Writeln(F,'<result property="razfilial" column="razfilial" />');
      Writeln(F,'<result property="nomefilial" column="nomefilial" />');
      Writeln(F,'<result property="mzfilial" column="mzfilial" />');
      Writeln(F,'<result property="cnpjfilial" column="cnpjfilial" />');
      Writeln(F,'<result property="inscfilial" column="inscfilial" />');
      Writeln(F,'<result property="coddistfilial" column="coddistfilial" />');
      Writeln(F,'<result property="percpisfilial" column="percpisfilial" />');
      Writeln(F,'<result property="perccofinsfilial" column="perccofinsfilial" />');
      Writeln(F,'<result property="percirfilial" column="percirfilial" />');
      Writeln(F,'<result property="perccsocialfilial" column="perccsocialfilial" />');
      Writeln(F,'<result property="simplesfilial" column="simplesfilial" />');
      Writeln(F,'<result property="percsimplesfilial" column="percsimplesfilial" />');
      Writeln(F,'<result property="codmunic" column="codmunic" />');
      Writeln(F,'<result property="siglauf" column="siglauf" />');
      Writeln(F,'<result property="codpais" column="codpais" />');
      Writeln(F,'<result property="codempuc" column="codempuc" />');
      Writeln(F,'<result property="codfilialuc" column="codfilialuc" />');
      Writeln(F,'<result property="codunifcod" column="codunifcod" />');
      Writeln(F,'<result property="inscmunfilial" column="inscmunfilial" />');
      Writeln(F,'<result property="cnaefilial" column="cnaefilial" />');
      Writeln(F,'<result property="percissfilial" column="percissfilial" />');
      Writeln(F,'<result property="contribipifilial" column="contribipifilial" />');
      Writeln(F,'<result property="timbrefilial" column="timbrefilial" />');
      Writeln(F,'<result property="perfilfilial" column="perfilfilial" />');
      Writeln(F,'<result property="indativfilial" column="indativfilial" />');
      Writeln(F,'<result property="dtins" column="dtins" />');
      Writeln(F,'<result property="hins" column="hins" />');
      Writeln(F,'<result property="idusuins" column="idusuins" />');
      Writeln(F,'<result property="dtalt" column="dtalt" />');
      Writeln(F,'<result property="halt" column="halt" />');
      Writeln(F,'<result property="idusualt" column="idusualt" />');
      Writeln(F,'<result property="codempco" column="codempco" />');
      Writeln(F,'<result property="codfilialco" column="codfilialco" />');
      Writeln(F,'<result property="codfor" column="codfor" />');
      Writeln(F,'<result property="suframa" column="suframa" />');
      Writeln(F,'<result property="sedeMatriz" column="sedeMatriz" />');
      Writeln(F,'<collection property="codend" column="codend" ');
      Writeln(F,'select="Empresa.fetchAllEnderecoByFilial" />');
      Writeln(F,'</resultMap>');

      Writeln(F,'<resultMap id="EnderecoResult" type="Endereco">');
      Writeln(F,'<result property="codend" column="codend" />');
      Writeln(F,'<result property="endereco" column="ende" />');
      Writeln(F,'<result property="numero" column="num" />');
      Writeln(F,'<result property="complemento" column="compl" />');
      Writeln(F,'<result property="bairro" column="bair" />');
      Writeln(F,'<result property="cep" column="cep" />');
      Writeln(F,'<result property="cidade" column="cid" />');
      Writeln(F,'<result property="uf" column="uf" />');
      Writeln(F,'<result property="ddd" column="ddd" />');
      Writeln(F,'<result property="fone1" column="fone" />');
      Writeln(F,'<result property="fone2" column="fone" />');
      Writeln(F,'<result property="email" column="email" />');
      Writeln(F,'<result property="site" column="www" />');
      Writeln(F,'<result property="cel1" column="fone" />');
      Writeln(F,'<result property="cel2" column="fone" />');
      Writeln(F,'<result property="codpais" column="codpais" />');
      Writeln(F,'<result property="codmunic" column="codmunic" />');
      Writeln(F,'<!--  	<result property="siglauf" column="siglauf" />');
      Writeln(F,'<result property="dtins" column="dtins" />');
      Writeln(F,'<result property="hins" column="hins" />');
      Writeln(F,'<result property="idusuins" column="idusuins" />');
      Writeln(F,'<result property="dtalt" column="dtalt" />');
      Writeln(F,'<result property="halt" column="halt" />');
      Writeln(F,'<result property="idusualt" column="idusualt" />');
      Writeln(F,'</resultMap>');

      Writeln(F,'<sql id="allEmpresaColumms">');
      Writeln(F,'SELECT codemp, razemp, nomeemp, cnpjemp, inscemp, codend, codean, multialmoxemp,');
      Writeln(F,'fotoemp, codmunic, percissemp, dtins, hins, dtalt, halt, idusuins ');
      Writeln(F,'</sql>');

      Writeln(F,'<!-- Fetch All Tags -->');
      Writeln(F,'<select id="fetchAllEmpresas" parameterType="Map" resultMap="EmpresasResult">');

      Writeln(F,'SELECT codemp, razemp, nomeemp, cnpjemp, inscemp, codend, codean, multialmoxemp, ');
      Writeln(F,'fotoemp, codmunic, percissemp, dtins, hins, dtalt, halt, idusuins   ');
      Writeln(F,'FROM empresa;   ');

      Writeln(F,'</select>');

      Writeln(F,'<select id="fetchAllFiliaisById"  parameterType="Map" resultMap="FilialResult">');

      Writeln(F,'select f.* ');
      Writeln(F,'from filial f ,empresa e   ');
      Writeln(F,'where   ');
      Writeln(F,'f.codemp = e.codemp and  ');
      Writeln(F,'f.codemp = #{codemp}  ');

      Writeln(F,'</select>');

      Writeln(F,'<select id="fetchAllEnderecoByFilial"  resultMap="EnderecoResult">');

      Writeln(F,'select e.*  ');
      Writeln(F,'from filial f  ');
      Writeln(F,'inner join endereco e on   ');
      Writeln(F,'(f.codend = e.codend and f.codfilial = #{codfilial} ) ');

      Writeln(F,'</select>');

      Writeln(F,'<select id="fetchAllEnderecoByEmpresa"  resultMap="EnderecoResult">');

      Writeln(F,'select n.*');
      Writeln(F,'from empresa e  ');
      Writeln(F,'left join endereco n on  ');
      Writeln(F,'(e.codend = n.codend and e.codemp = #{codemp})  ');

      Writeln(F,'</select>');

      Writeln(F,'<!-- Insert Empresa -->');
      Writeln(F,'<select id="insertEmpresa" parameterType="Empresa" resultType="int">');
      Writeln(F,'SELECT ins_empresa (   ');
      Writeln(F,'#{emdemp,jdbcType=VARCHAR}, ');
      Writeln(F,'#{numemp,jdbcType=INTEGER}, ');
      Writeln(F,'#{complemp,jdbcType=VARCHAR},  ');
      Writeln(F,'#{bairemp,jdbcType=VARCHAR},  ');
      Writeln(F,'#{cepemp,jdbcType=VARCHAR},  ');
      Writeln(F,'#{cidemp,jdbcType=VARCHAR},  ');
      Writeln(F,'#{ufemp,jdbcType=VARCHAR},   ');
      Writeln(F,'#{dddemp,jdbcType=VARCHAR},  ');
      Writeln(F,'#{foneemp,jdbcType=VARCHAR}, ');
      Writeln(F,'#{faxemp,jdbcType=VARCHAR},   ');
      Writeln(F,'#{emailemp,jdbcType=VARCHAR},  ');
      Writeln(F,'#{wwwemp,jdbcType=VARCHAR},    ');
      Writeln(F,'#{nomecontemp,jdbcType=VARCHAR}, ');
      Writeln(F,'#{siglauf,jdbcType=VARCHAR},     ');
      Writeln(F,'#{codmunic,jdbcType=VARCHAR},   ');
      Writeln(F,'#{codpais,jdbcType=VARCHAR},    ');
      Writeln(F,'#{razemp,jdbcType=VARCHAR},     ');
      Writeln(F,'#{nomeemp,jdbcType=VARCHAR},    ');
      Writeln(F,'#{cnpjemp,jdbcType=VARCHAR},     ');
      Writeln(F,'#{inscemp,jdbcType=VARCHAR},      ');
      Writeln(F,'#{codeanemp,jdbcType=VARCHAR},    ');
      Writeln(F,'#{multialmoxemp,jdbcType=VARCHAR}, ');
      Writeln(F,'#{fotoemp,jdbcType=VARCHAR},      ');
      Writeln(F,'#{codmunic,jdbcType=VARCHAR},      ');
      Writeln(F,'#{percissemp,jdbcType=DOUBLE})     ');
      Writeln(F,'</select>');

      Writeln(F,'<select id="insertEndereco" parameterType="Empresa" resultType="int">');
      Writeln(F,'SELECT ins_endereco( ');
      Writeln(F,'#{emdemp,jdbcType=VARCHAR}, ');
      Writeln(F,'#{numemp,jdbcType=INTEGER},  ');
      Writeln(F,'#{complemp,jdbcType=VARCHAR},  ');
      Writeln(F,'#{bairemp,jdbcType=VARCHAR}, ');
      Writeln(F,'#{cepemp,jdbcType=VARCHAR},  ');
      Writeln(F,'#{cidemp,jdbcType=VARCHAR}, ');
      Writeln(F,'#{ufemp,jdbcType=VARCHAR}, ');
      Writeln(F,'#{dddemp,jdbcType=VARCHAR},  ');
      Writeln(F,'#{foneemp,jdbcType=VARCHAR},  ');
      Writeln(F,'#{faxemp,jdbcType=VARCHAR},   ');
      Writeln(F,'#{emailemp,jdbcType=VARCHAR},  ');
      Writeln(F,'#{wwwemp,jdbcType=VARCHAR},     ');
      Writeln(F,'#{nomecontemp,jdbcType=VARCHAR}, ');
      Writeln(F,'#{siglauf,jdbcType=VARCHAR},  ');
      Writeln(F,'#{codmunic,jdbcType=VARCHAR}, ');
      Writeln(F,'#{codpais,jdbcType=VARCHAR})  ');
      Writeln(F,'</select>');
      Writeln(F,'</mapper>');
      Closefile(F);
end;
function TForm1.criarCodeIClasseDACImpl(Txt:String):String;
begin
      AssignFile(F,'c:\I'+PrimeiraMaiscula(Edit1.Text)+'DAC.java');
      Writeln(F,'package com.sensus.mlc.empresa.dac.mybatis;');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'import java.util.Date;');
      Writeln(F,'import java.util.HashMap;');
      Writeln(F,'import java.util.List;');
      Writeln(F,'import java.util.Map;');
      Writeln(F,'');
      Writeln(F,'import org.mybatis.spring.support.SqlSessionDaoSupport;');
      Writeln(F,'import static com.sensus.common.util.SensusMyBatisDacHelper.doInsert;');
      Writeln(F,'import static com.sensus.common.util.SensusMyBatisDacHelper.doQueryForList;');
      Writeln(F,'import static com.sensus.common.util.SensusMyBatisDacHelper.doQueryForObject;');
      Writeln(F,'import static com.sensus.common.util.SensusMyBatisDacHelper.doRemove;');
      Writeln(F,'import static com.sensus.common.util.SensusMyBatisDacHelper.doUpdate;');
      Writeln(F,'import static com.sensus.mlc.base.util.LCHelp.createInquiryLightRequest;');
      Writeln(F,'import static com.sensus.mlc.smartpoint.dacd.SmartPointDACD.getParametersToFetchAllLights;');
      Writeln(F,'');
      Writeln(F,'import com.sensus.common.model.request.Request;');
      Writeln(F,'import com.sensus.common.model.response.InternalResponse;');
      Writeln(F,'import com.sensus.common.model.response.InternalResultsResponse;');
      Writeln(F,'import com.sensus.common.validation.ValidationUtil;');
      Writeln(F,'import com.sensus.mlc.empresa.dac.IEmpresaDAC;');
      Writeln(F,'import com.sensus.mlc.empresa.model.Empresa;');
      Writeln(F,'import com.sensus.mlc.empresa.model.request.EmpresaRequest;');
      Writeln(F,'import com.sensus.mlc.empresa.model.request.InquiryEmpresaRequest;');
      Writeln(F,'import com.sensus.mlc.empresa.model.response.EmpresaResponse;');
      Writeln(F,'');
      Writeln(F,'/**');
      Writeln(F,'* The Class ActionDACImpl.');
      Writeln(F,'*');
      Writeln(F,'* @author - QAT Brazil.');
      Writeln(F,'*');
      Writeln(F,'*/');
      Writeln(F,'public class EmpresaDACImpl extends SqlSessionDaoSupport implements IEmpresaDAC');
      Writeln(F,'{');
      Writeln(F,'');
      Writeln(F,'/** The Constant PARAMSIZE7. */');
      Writeln(F,'');
      Writeln(F,'/** The Constant PARAMSIZE1. */');
      Writeln(F,'');
      Writeln(F,'/** The Constant TAG_NAMESPACE. */');
      Writeln(F,'private static final String EMPRESA_NAMESPACE = "Empresa.";');
      Writeln(F,'');
      Writeln(F,'/** The Constant FETCH_ALL_TAGS. */');
      Writeln(F,'private static final String FETCH_ALL_EMPRESAS = EMPRESA_NAMESPACE + "fetchAllEmpresas";');
      Writeln(F,'');
      Writeln(F,'private static final Integer PARAMSIZE1 = 1;');
      Writeln(F,'');
      Writeln(F,'/** The Constant PARAMSIZE6. */');
      Writeln(F,'private static final Integer PARAMSIZE6 = 6;');
      Writeln(F,'');
      Writeln(F,'/** The Constant PARAMSIZE6. */');
      Writeln(F,'private static final Integer PARAMSIZE32 = 32;');
      Writeln(F,'');
      Writeln(F,'/** The Constant PARAMSIZE7. */');
      Writeln(F,'private static final Integer PARAMSIZE7 = 7;');
      Writeln(F,'');
      Writeln(F,'/** The Constant TOTAL_COLUMN. */');
      Writeln(F,'private static final Integer TOTAL_COLUMN = 5;');
      Writeln(F,'');
      Writeln(F,'/** The Constant COLUMN_0. */');
      Writeln(F,'private static final Integer COLUMN_0 = 0;');
      Writeln(F,'');
      Writeln(F,'/** The Constant COLUMN_1. */');
      Writeln(F,'private static final Integer COLUMN_1 = 1;');
      Writeln(F,'');
      Writeln(F,'/** The Constant COLUMN_2. */');
      Writeln(F,'private static final Integer COLUMN_2 = 2;');
      Writeln(F,'');
      Writeln(F,'/** The Constant COLUMN_3. */');
      Writeln(F,'private static final Integer COLUMN_3 = 3;');
      Writeln(F,'');
      Writeln(F,'/** The Constant COLUMN_4. */');
      Writeln(F,'private static final Integer COLUMN_4 = 4;');
      Writeln(F,'');
      Writeln(F,'/** The Constant ACTION_NAME_HEADER. */');
      Writeln(F,'private static final String ACTION_NAME_HEADER = "Action Name";');
      Writeln(F,'');
      Writeln(F,'/** The Constant PAGINATION_TOTAL_ROWS. */');
      Writeln(F,'private static final String PAGINATION_TOTAL_ROWS = EMPRESA_NAMESPACE + "PaginationTotalRows";');
      Writeln(F,'');
      Writeln(F,'/** The Constant ORDERBY. */');
      Writeln(F,'private static final String ORDERBY = "orderBy";');
      Writeln(F,'');
      Writeln(F,'/** The Constant GROUPID. */');
      Writeln(F,'private static final String EMPRESA_ID = "codEmp";');
      Writeln(F,'');
      Writeln(F,'/** The Constant START_PAGE. */');
      Writeln(F,'private static final String START_PAGE = "startPage";');
      Writeln(F,'');
      Writeln(F,'/** The Constant ACTION_TYPE_HEADER. */');
      Writeln(F,'private static final String ACTION_TYPE_HEADER = "Action Type";');
      Writeln(F,'');
      Writeln(F,'/** The Constant MODIFIED_BY_HEADER. */');
      Writeln(F,'private static final String MODIFIED_BY_HEADER = "Modified By";');
      Writeln(F,'');
      Writeln(F,'/** The Constant DATE_MODIFIED_HEADER. */');
      Writeln(F,'private static final String DATE_MODIFIED_HEADER = "Date Modified";');
      Writeln(F,'');
      Writeln(F,'/** The Constant LOCKED_HEADER. */');
      Writeln(F,'private static final String LOCKED_HEADER = "Locked";');
      Writeln(F,'');
      Writeln(F,'private static final String TENANT_ID = "tenantId";');
      Writeln(F,'');
      Writeln(F,'/** The Constant ORDER_BY. */');
      Writeln(F,'private static final String ORDER_BY = "order_by";');
      Writeln(F,'');
      Writeln(F,'/** The Constant SORT_BY. */');
      Writeln(F,'private static final String SORT_BY = "sort_by";');
      Writeln(F,'');
      Writeln(F,'/** The Constant PAGE_SIZE. */');
      Writeln(F,'private static final String PAGE_SIZE = "page_size";');
      Writeln(F,'');
      Writeln(F,'/** The Constant START_ROW. */');
      Writeln(F,'private static final String START_ROW = "start_row";');
      Writeln(F,'');
      Writeln(F,'/** The Constant ACTION_NAME. */');
      Writeln(F,'private static final String ACTION_NAME = "action_name";');
      Writeln(F,'');
      Writeln(F,'/** The Constant ACTION_TYPES. */');
      Writeln(F,'private static final String ACTION_TYPES = "action_types";');
      Writeln(F,'');
      Writeln(F,'/** The Constant USERS. */');
      Writeln(F,'private static final String USERS = "users";');
      Writeln(F,'');
      Writeln(F,'/** The Constant ACTION_ID. */');
      Writeln(F,'private static final String ACTION_ID = "action_id";');
      Writeln(F,'');
      Writeln(F,'/** The Constant ACTION_TYPE. */');
      Writeln(F,'private static final String ACTION_TYPE = "action_type";');
      Writeln(F,'');
      Writeln(F,'/** The Constant ACTION_DESCRIPTION. */');
      Writeln(F,'private static final String ACTION_DESCRIPTION = "action_description";');
      Writeln(F,'');
      Writeln(F,'/** The Constant START_STEP. */');
      Writeln(F,'private static final String START_STEP = "start_step";');
      Writeln(F,'');
      Writeln(F,'/** The Constant CREATE_USER. */');
      Writeln(F,'private static final String CREATE_USER = "create_user";');
      Writeln(F,'');
      Writeln(F,'/** The Constant STEP_LIST. */');
      Writeln(F,'private static final String STEP_LIST = "step_list";');
      Writeln(F,'');
      Writeln(F,'/** The Constant DEMAND_RESET_STEP_LIST. */');
      Writeln(F,'private static final String DEMAND_RESET_STEP_LIST = "1,2,3,4";');
      Writeln(F,'');
      Writeln(F,'/** The Constant UNSELECTION_PAGINATION_IDS. */');
      Writeln(F,'private static final String UNSELECTION_PAGINATION_IDS = "unselectionPaginationIds";');
      Writeln(F,'');
      Writeln(F,'/** The Constant INSERT_SMART_POINT_TO_TAG. */');
      Writeln(F,'private static final String INSERT_SMART_POINT_TO_TAG = EMPRESA_NAMESPACE + "insertSmartPointToTag";');
      Writeln(F,'');
      Writeln(F,'/** The Constant INSERT_TAG. */');
      Writeln(F,'private static final String INSERT_EMPRESA = EMPRESA_NAMESPACE + "insertEmpresa";');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'/** The Constant SENSUS_EPM_ACTIONVALIDATOR_ACTION_IS_SCHEDULED. */');
      Writeln(F,'private static final String SENSUS_EPM_ACTIONVALIDATOR_ACTION_IS_SCHEDULED =');
      Writeln(F,'"sensus.epm.actionvalidator.action.is_scheduled";');
      Writeln(F,'');
      Writeln(F,'/** The Constant ADD_ACTION_FAILED. */');
      Writeln(F,'private static final String ADD_ACTION_FAILED = "sensus.epm.actionbclimpl.add.action.failed";');
      Writeln(F,'');
      Writeln(F,'/**');
      Writeln(F,'* Prepare data to write file.');
      Writeln(F,'*');
      Writeln(F,'* @param actionList the action list');
      Writeln(F,'* @return the string[][]');
      Writeln(F,'*/');
      Writeln(F,'private String[][] preapreDataToWriteFile(List<Empresa> actionList)');
      Writeln(F,'{');
      Writeln(F,'String[][] excelData = new String[actionList.size() + 1][TOTAL_COLUMN];');
      Writeln(F,'');
      Writeln(F,'// HEADER');
      Writeln(F,'excelData[0][COLUMN_0] = ACTION_NAME_HEADER;');
      Writeln(F,'excelData[0][COLUMN_1] = ACTION_TYPE_HEADER;');
      Writeln(F,'excelData[0][COLUMN_2] = MODIFIED_BY_HEADER;');
      Writeln(F,'excelData[0][COLUMN_3] = DATE_MODIFIED_HEADER;');
      Writeln(F,'excelData[0][COLUMN_4] = LOCKED_HEADER;');
      Writeln(F,'');
      Writeln(F,'for (int i = 1; i <= actionList.size(); i++)');
      Writeln(F,'{ ');
      Writeln(F,'Empresa empresa = actionList.get(i - 1);');
      Writeln(F,'');
      Writeln(F,'excelData[i][COLUMN_0] = empresa.getCodemp().toString();');
      Writeln(F,'');
      Writeln(F,'excelData[i][COLUMN_1] = null;');
      Writeln(F,'if (!ValidationUtil.isNull(empresa.getNomeemp()))');
      Writeln(F,'{');
      Writeln(F,'excelData[i][COLUMN_1] = empresa.getRazemp();');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'excelData[i][COLUMN_2] = empresa.getCnpjemp();');
      Writeln(F,'');
      Writeln(F,'excelData[i][COLUMN_3] = null;');
      Writeln(F,'if (!ValidationUtil.isNull(empresa.getInscemp()))');
      Writeln(F,'{');
      Writeln(F,'excelData[i][COLUMN_3] = empresa.getInscemp();');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'excelData[i][COLUMN_4] = null;');
      Writeln(F,'if (!ValidationUtil.isNull(empresa.getCodmunic()))');
      Writeln(F,'{');
      Writeln(F,'excelData[i][COLUMN_4] = empresa.getWwwemp();');
      Writeln(F,'}');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'return excelData;');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'@Override');
      Writeln(F,'public InternalResultsResponse<Empresa> insertEmpresa(EmpresaRequest empresaRequest)');
      Writeln(F,'{');
      Writeln(F,'');
      Writeln(F,'// Define user from context.');
      Writeln(F,'empresaRequest.getEmpresa().setCreateUser(empresaRequest.getUserContext().getUserId());');
      Writeln(F,'');
      Writeln(F,'paramMap.put(UNSELECTION_PAGINATION_IDS, null);');
      Writeln(F,'');
      Writeln(F,'if (!ValidationUtil.isNullOrEmpty(empresaRequest.getUnselectionPaginationIds()))');
      Writeln(F,'{');
      Writeln(F,'paramMap.put(UNSELECTION_PAGINATION_IDS, empresaRequest.getUnselectionPaginationIds());');
      Writeln(F,'}');
      Writeln(F,'empresa.setCodemp((Integer)doQueryForObject(getSqlSession(), "insertEndereco", empresaRequest.getEmpresa()));');
      Writeln(F,'');
      Writeln(F,'InternalResultsResponse<Empresa> response = new InternalResultsResponse<Empresa>();');
      Writeln(F,'response.addResult(empresa);');
      Writeln(F,'return response;');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'@SuppressWarnings("unchecked")');
      Writeln(F,'@Override');
      Writeln(F,'public InternalResultsResponse<Empresa> fetchAllEmpresa(InquiryEmpresaRequest inquiryempresaRequest)');
      Writeln(F,'{');
      Writeln(F,'InternalResultsResponse<Empresa> response = new InternalResultsResponse<Empresa>();');
      Writeln(F,'HashMap<String, Object> paramMap = new HashMap<String, Object>(PARAMSIZE6);');
      Writeln(F,'paramMap.put(TENANT_ID, inquiryempresaRequest.getTenant().getId());');
      Writeln(F,'paramMap.put(PAGE_SIZE, inquiryempresaRequest.getPageSize());');
      Writeln(F,'paramMap.put(START_ROW, inquiryempresaRequest.getStartRow());');
      Writeln(F,'paramMap.put(START_PAGE, inquiryempresaRequest.getStartPage());');
      Writeln(F,'paramMap.put(ORDERBY, TagOrderByEnum.NAME_COLUMN.getValue());');
      Writeln(F,'');
      Writeln(F,'if (!ValidationUtil.isNullOrEmpty(inquiryempresaRequest.getSortExpressions()))');
      Writeln(F,'{');
      Writeln(F,'paramMap.put(ORDERBY, inquiryempresaRequest.getSortExpressions().get(0));');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'if (!ValidationUtil.isNull(inquiryempresaRequest.getEmpresas()))');
      Writeln(F,'{');
      Writeln(F,'paramMap.put(EMPRESA_ID, inquiryempresaRequest.getEmpresas().get(0).getCodemp());');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'doQueryForList(getSqlSession(), FETCH_ALL_EMPRESAS, paramMap, response);');
      Writeln(F,'');
      Writeln(F,'Integer totalRows = (Integer)doQueryForObject(getSqlSession(),');
      Writeln(F,'PAGINATION_TOTAL_ROWS, paramMap);');
      Writeln(F,'');
      Writeln(F,'response.getResultsSetInfo().setTotalRowsAvailable(totalRows);');
      Writeln(F,'return response;');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'@Override');
      Writeln(F,'public InternalResultsResponse<Empresa> fetchEmpresaById(EmpresaRequest empresaRequest)');
      Writeln(F,'{');
      Writeln(F,'InternalResultsResponse<Empresa> response = new InternalResultsResponse<Empresa>();');
      Writeln(F,'');
      Writeln(F,'response.getResultsList().addAll(');
      Writeln(F,'getSqlSession().selectList("EmpresaMap.fetchEmpresaById", empresaRequest.getEmpresa()));');
      Writeln(F,'');
      Writeln(F,'return response;');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'@Override');
      Writeln(F,'public InternalResponse generateFileCSV(InquiryEmpresaRequest inquiryEmpresaRequest)');
      Writeln(F,'{');
      Writeln(F,'InternalResponse response = new InternalResponse();');
      Writeln(F,'');
      Writeln(F,'preapreDataToWriteFile(inquiryEmpresaRequest.getEmpresas());');
      Writeln(F,'');
      Writeln(F,'if (GenerateFileCSV.generateCSVFile(inquiryEmpresaRequest.getFileName(), excelData))');
      Writeln(F,'{');
      Writeln(F,'response.setStatus(Status.OperationSuccess);');
      Writeln(F,'}');
      Writeln(F,'else');
      Writeln(F,'{');
      Writeln(F,'response.setStatus(Status.ExceptionError);');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'return response;');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'@Override');
      Writeln(F,'public EmpresaResponse fetchAllEmpresaTypes(Request request)');
      Writeln(F,'{');
      Writeln(F,'// TODO Auto-generated method stub');
      Writeln(F,'return null;');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'@Override');
      Writeln(F,'public EmpresaResponse fetchAllEmpresaFilial(Request request)');
      Writeln(F,'{');
      Writeln(F,'// TODO Auto-generated method stub');
      Writeln(F,'return null;');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'@Override');
      Writeln(F,'public InternalResultsResponse<Empresa> updateEmpresa(');
      Writeln(F,'EmpresaRequest empresaRequest) {');
      Writeln(F,'// TODO Auto-generated method stub');
      Writeln(F,'return null;');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'@Override');
      Writeln(F,'public InternalResponse deleteEmpresa(EmpresaRequest empresaRequest) {');
      Writeln(F,'// TODO Auto-generated method stub');
      Writeln(F,'return null;');
      Writeln(F,'}');
      Writeln(F,'');
      Writeln(F,'}');
      Writeln(F,'');
      Closefile(F);
end;

 function TForm1.criarCodeIClasseDAC(Txt:String):String;
 begin
        AssignFile(F,'c:\I'+PrimeiraMaiscula(Edit1.Text)+'DAC.java');
        Writeln(F,'package com.sensus.mlc.empresa.dac');
        Writeln(F,'');
        Writeln(F,'');
        Writeln(F,'import com.sensus.common.model.request.Request');
        Writeln(F,'import com.sensus.common.model.response.InternalResponse');
        Writeln(F,'import com.sensus.common.model.response.InternalResultsResponse');
        Writeln(F,'import com.sensus.mlc.empresa.model.Empresa');
        Writeln(F,'import com.sensus.mlc.empresa.model.request.EmpresaRequest');
        Writeln(F,'import com.sensus.mlc.empresa.model.request.InquiryEmpresaRequest');
        Writeln(F,'import com.sensus.mlc.empresa.model.response.EmpresaResponse');
        Writeln(F,'');
        Writeln(F,'/**');
        Writeln(F,'* The Interface IActionDAC.');
        Writeln(F,'*');
        Writeln(F,'* @author - QAT Brazil.');
        Writeln(F,'*');
        Writeln(F,'*/');
        Writeln(F,'public interface IEmpresaDAC');
        Writeln(F,'{');
        Writeln(F,'');
        Writeln(F,'/**');
        Writeln(F,'* Update empresa.');
        Writeln(F,'*');
        Writeln(F,'* @param empresaRequest the empresa request');
        Writeln(F,'* @return the empresa response');
        Writeln(F,'*/');
        Writeln(F,'public InternalResultsResponse<Empresa> updateEmpresa(EmpresaRequest empresaRequest)');
        Writeln(F,'');
        Writeln(F,'/**');
        Writeln(F,'* Delete empresa.');
        Writeln(F,'*');
        Writeln(F,'* @param empresaRequest the empresa request');
        Writeln(F,'* @return the empresa response');
        Writeln(F,'*/');
        Writeln(F,'public InternalResponse deleteEmpresa(EmpresaRequest empresaRequest)');
        Writeln(F,'');
        Writeln(F,'/**');
        Writeln(F,'* Fetch all empresa.');
        Writeln(F,'*');
        Writeln(F,'* @param inquiryempresaRequest the inquiryempresa request');
        Writeln(F,'* @return the inquiry empresa response');
        Writeln(F,'*/');
        Writeln(F,'public InternalResultsResponse<Empresa> fetchAllEmpresa(InquiryEmpresaRequest inquiryempresaRequest)');
        Writeln(F,'');
        Writeln(F,'/**');
        Writeln(F,'* Fetch empresa by id.');
        Writeln(F,'*');
        Writeln(F,'* @param inquiryempresaRequest the inquiryempresa request');
        Writeln(F,'* @return the internal results response');
        Writeln(F,'*/');
        Writeln(F,'public InternalResultsResponse<Empresa> fetchEmpresaById(EmpresaRequest empresaRequest)');
        Writeln(F,'');
        Writeln(F,'/**');
        Writeln(F,'* Generate file csv.');
        Writeln(F,'*');
        Writeln(F,'* @param inquiryEmpresaRequest the inquiry empresa request');
        Writeln(F,'* @return the inquiry empresa response');
        Writeln(F,'*/');
        Writeln(F,'public InternalResponse generateFileCSV(InquiryEmpresaRequest inquiryEmpresaRequest)');
        Writeln(F,'');
        Writeln(F,'/**');
        Writeln(F,'* Fetch all empresa types.');
        Writeln(F,'*');
        Writeln(F,'* @param request the request');
        Writeln(F,'* @return the empresa response');
        Writeln(F,'*/');
        Writeln(F,'public EmpresaResponse fetchAllEmpresaTypes(Request request)');
        Writeln(F,'');
        Writeln(F,'/**');
        Writeln(F,'* Fetch all empresa filial.');
        Writeln(F,'*');
        Writeln(F,'* @param request the request');
        Writeln(F,'* @return the empresa response');
        Writeln(F,'*/');
        Writeln(F,'public EmpresaResponse fetchAllEmpresaFilial(Request request)');
        Writeln(F,'');
        Writeln(F,'public InternalResultsResponse<Empresa> insertEmpresa(EmpresaRequest empresaRequest)');
        Writeln(F,'}');
        Writeln(F,'');
        Writeln(F,'');
        Closefile(F);
 end;

function TForm1.criarCodeIClasseBCLImpl(Txt:String):String;
begin
      AssignFile(F,'c:\'+PrimeiraMaiscula(Edit1.Text)+'BCLImpl.java');
      Writeln(F,'package com.sensus.mlc.empresa.bcl.impl; ');
      Writeln(F,' ');
      Writeln(F,'import static com.sensus.mlc.base.util.LCHelp.createProcessItemWithFailure; ');
      Writeln(F,'import static com.sensus.mlc.base.util.LCHelp.createProcessRequest; ');
      Writeln(F,'  ');
      Writeln(F,'import java.util.ArrayList; ');
      Writeln(F,'import java.util.List; ');
      Writeln(F,' ');
      Writeln(F,'import org.apache.commons.logging.Log; ');
      Writeln(F,'import org.apache.commons.logging.LogFactory; ');
      Writeln(F,'  ');
      Writeln(F,'import com.sensus.common.model.response.InternalResponse; ');
      Writeln(F,'import com.sensus.common.model.response.InternalResultsResponse; ');
      Writeln(F,'import com.sensus.common.util.SensusAppContext; ');
      Writeln(F,'import com.sensus.common.validation.ValidationUtil; ');
      Writeln(F,'import com.sensus.mlc.base.util.LCDateUtil;   ');
      Writeln(F,'import com.sensus.mlc.base.util.LCHelp;        ');
      Writeln(F,'import com.sensus.mlc.empresa.bcl.IEmpresaBCL; ');
      Writeln(F,'import com.sensus.mlc.empresa.dac.IEmpresaDAC;  ');
      Writeln(F,'import com.sensus.mlc.empresa.model.Empresa;    ');
      Writeln(F,'import com.sensus.mlc.empresa.model.request.EmpresaRequest; ');
      Writeln(F,'import com.sensus.mlc.empresa.model.request.InquiryEmpresaRequest;  ');
      Writeln(F,'import com.sensus.mlc.process.bcl.IProcessBCL;    ');
      Writeln(F,'import com.sensus.mlc.process.model.LCAction;  ');
      Writeln(F,'import com.sensus.mlc.process.model.LCActionParameter;  ');
      Writeln(F,'import com.sensus.mlc.process.model.LCActionTypeEnum;  ');
      Writeln(F,'import com.sensus.mlc.process.model.Process;   ');
      Writeln(F,'import com.sensus.mlc.process.model.ProcessItemStatusEnum; ');
      Writeln(F,'import com.sensus.mlc.process.model.ProcessStatusReasonEnum; ');
      Writeln(F,'import com.sensus.mlc.process.model.request.ProcessRequest; ');
      Writeln(F,'import com.sensus.mlc.schedule.bcl.IScheduleBCL;  ');
      Writeln(F,'import com.sensus.mlc.smartpoint.model.Light; ');
      Writeln(F,'import com.sensus.mlc.smartpoint.model.PropertyEnum; ');
      Writeln(F,'import com.sensus.mlc.smartpoint.model.SearchParameter;');
      Writeln(F,'  ');
      Writeln(F,'/** ');
      Writeln(F,' * Action BCL implementation class. ');
      Writeln(F,' * ');
      Writeln(F,' * @author QAT. ');
      Writeln(F,' */');
      Writeln(F,'public class EmpresaBCLImpl implements IEmpresaBCL ');
      Writeln(F,'package com.sensus.mlc.empresa.bcl.impl');
      Writeln(F,' ');
      Writeln(F,'import static com.sensus.mlc.base.util.LCHelp.createProcessItemWithFailure');
      Writeln(F,'import static com.sensus.mlc.base.util.LCHelp.createProcessRequest');
      Writeln(F,' ');
      Writeln(F,'import java.util.ArrayList');
      Writeln(F,'import java.util.List');
      Writeln(F,' ');
      Writeln(F,'import org.apache.commons.logging.Log');
      Writeln(F,'import org.apache.commons.logging.LogFactory');
      Writeln(F,' ');
      Writeln(F,'import com.sensus.common.model.response.InternalResponse');
      Writeln(F,'import com.sensus.common.model.response.InternalResultsResponse');
      Writeln(F,'import com.sensus.common.util.SensusAppContext');
      Writeln(F,'import com.sensus.common.validation.ValidationUtil');
      Writeln(F,'import com.sensus.mlc.base.util.LCDateUtil');
      Writeln(F,'import com.sensus.mlc.base.util.LCHelp');
      Writeln(F,'import com.sensus.mlc.empresa.bcl.IEmpresaBCL');
      Writeln(F,'import com.sensus.mlc.empresa.dac.IEmpresaDAC');
      Writeln(F,'import com.sensus.mlc.empresa.model.Empresa');
      Writeln(F,'import com.sensus.mlc.empresa.model.request.EmpresaRequest');
      Writeln(F,'import com.sensus.mlc.empresa.model.request.InquiryEmpresaRequest');
      Writeln(F,'import com.sensus.mlc.process.bcl.IProcessBCL');
      Writeln(F,'import com.sensus.mlc.process.model.LCAction');
      Writeln(F,'import com.sensus.mlc.process.model.LCActionParameter');
      Writeln(F,'import com.sensus.mlc.process.model.LCActionTypeEnum');
      Writeln(F,'import com.sensus.mlc.process.model.Process');
      Writeln(F,'import com.sensus.mlc.process.model.ProcessItemStatusEnum');
      Writeln(F,'import com.sensus.mlc.process.model.ProcessStatusReasonEnum');
      Writeln(F,'import com.sensus.mlc.process.model.request.ProcessRequest');
      Writeln(F,'import com.sensus.mlc.schedule.bcl.IScheduleBCL');
      Writeln(F,'import com.sensus.mlc.smartpoint.model.Light');
      Writeln(F,'import com.sensus.mlc.smartpoint.model.PropertyEnum');
      Writeln(F,'import com.sensus.mlc.smartpoint.model.SearchParameter');
      Writeln(F,' ');
      Writeln(F,'/**');
      Writeln(F,'* Action BCL implementation class. ');
      Writeln(F,'*');
      Writeln(F,'* @author QAT. ');
      Writeln(F,'*/');
      Writeln(F,'public class EmpresaBCLImpl implements IEmpresaBCL ');
      Writeln(F,'{ ');
      Writeln(F,' ');
      Writeln(F,'/** The LOG. */  ');
      Writeln(F,'private static transient Log LOG = LogFactory.getLog(EmpresaBCLImpl.class)');
      Writeln(F,' ');
      Writeln(F,'/** The empresa dac. */ ');
      Writeln(F,'private IEmpresaDAC empresaDAC // injected by Spring through setter ');
      Writeln(F,' ');
      Writeln(F,'/** The Constant PROCESS_BCL_BEAN. */ ');
      Writeln(F,'private static final String PROCESS_BCL_BEAN = "processBCLTarget"');
      Writeln(F,' ');
      Writeln(F,'/** The Constant SCHEDULE_BCL_BEAN. */ ');
      Writeln(F,'private static final String SCHEDULE_BCL_BEAN = "scheduleBCLTarget"');
      Writeln(F,' ');
      Writeln(F,'/** The Constant ACTION_PROVIDER_TYPE. */ ');
      Writeln(F,'private static final String ACTION_PROVIDER_TYPE = "EPM.TASK"');
      Writeln(F,' ');
      Writeln(F,'/** The Constant ADD_PROPERTY_TO_ACTION_FAILED. */ ');
      Writeln(F,'private static final String ADD_PROPERTY_TO_ACTION_FAILED =  ');
      Writeln(F,'"sensus.epm.actionbclimpl.add.property.to.action.failed"');
      Writeln(F,' ');
      Writeln(F,'/** The Constant UPDATE_PROPERTY_TO_ACTION_FAILED. */  ');
      Writeln(F,'private static final String UPDATE_PROPERTY_TO_ACTION_FAILED = ');
      Writeln(F,'"sensus.epm.actionbclimpl.update.property.to.action.failed"');
      Writeln(F,' ');
      Writeln(F,'/** The Constant DELETE_PROPERTY_FROM_ACTION_FAILED. */   ');
      Writeln(F,'private static final String DELETE_PROPERTY_FROM_ACTION_FAILED = ');
      Writeln(F,'"sensus.epm.actionbclimpl.delete.property.from.action.failed"');
      Writeln(F,' ');
      Writeln(F,'/** The Constant PROPERTY_DAC_BEAN. */ ');
      Writeln(F,'private static final String PROPERTY_DAC_BEAN = "propertyDACTarget"');
      Writeln(F,' ');
      Writeln(F,'/** The Constant GET_ACTION_TO_CLONE_FAILED. */     ');
      Writeln(F,'private static final String GET_ACTION_TO_CLONE_FAILED = "sensus.epm.actionbclimpl.get.action.to.clone.failed"');
      Writeln(F,' ');
      Writeln(F,'/** The Constant APPLY_ACTION_FAILED. */   ');
      Writeln(F,'private static final String APPLY_ACTION_FAILED =  ');
      Writeln(F,'"sensus.epm.actionbclimpl.apply.action.failed"');
      Writeln(F,' ');
      Writeln(F,'/** The Constant DATE_RAND_DIVISION. */  ');
      Writeln(F,'private static final Integer DATE_RAND_DIVISION = 0xFFFFF');
      Writeln(F,' ');
      Writeln(F,'/**  ');
      Writeln(F,'* Gets the process bcl. ');
      Writeln(F,'*   ');
      Writeln(F,'* @return the process bcl ');
      Writeln(F,'*/');
      Writeln(F,'public IProcessBCL getProcessBCL() ');
      Writeln(F,'{  ');
      Writeln(F,'return (IProcessBCL)SensusAppContext.getApplicationContext().getBean(PROCESS_BCL_BEAN)');
      Writeln(F,'} ');
      Writeln(F,' ');
      Writeln(F,'/**');
      Writeln(F,'* Gets the schedule bcl. ');
      Writeln(F,'* ');
      Writeln(F,'* @return the schedule bcl ');
      Writeln(F,'*/');
      Writeln(F,'public IScheduleBCL getScheduleBCL()');
      Writeln(F,'{  ');
      Writeln(F,'return (IScheduleBCL)SensusAppContext.getApplicationContext().getBean(SCHEDULE_BCL_BEAN)');
      Writeln(F,'} ');
      Writeln(F,' ');
      Writeln(F,'@Override ');
      Writeln(F,'public InternalResultsResponse<Empresa> insertEmpresa(EmpresaRequest empresaRequest)  ');
      Writeln(F,'{  ');
      Writeln(F,'InternalResultsResponse<Empresa> response = getEmpresaDAC().insertEmpresa(empresaRequest)');
      Writeln(F,' ');
      Writeln(F,'if (!response.isInError())  ');
      Writeln(F,'{    ');
      Writeln(F,'Empresa empresa = response.getFirstResult()');
      Writeln(F,'empresaRequest.setEmpresa(empresa)');
      Writeln(F,' ');
      Writeln(F,'SearchParameter empresaParameter =  ');
      Writeln(F,'new SearchParameter(PropertyEnum.EMPRESA_ID, String.valueOf(empresa.getCodemp()))');
      Writeln(F,'empresaRequest.getSearchLight().addSearchParameter(empresaParameter)');
      Writeln(F,'InternalResultsResponse<Process> processResponse =   ');
      Writeln(F,'insertProcess(empresaRequest, LCActionTypeEnum.INSERT_EMPRESA, null)');
      Writeln(F,'empresaRequest.getSearchLight().getSearchParameters().remove(empresaParameter)');
      Writeln(F,' ');
      Writeln(F,'response.setStatus(processResponse.getStatus())');
      Writeln(F,'response.addMessages(processResponse.getMessageInfoList())');
      Writeln(F,'}  ');
      Writeln(F,'return response');
      Writeln(F,' ');
      Writeln(F,'}  ');
      Writeln(F,' ');
      Writeln(F,'@Override ');
      Writeln(F,'public InternalResultsResponse<Empresa> updateEmpresa(EmpresaRequest empresaRequest)');
      Writeln(F,'{ ');
      Writeln(F,'InternalResponse groupResponse = new InternalResponse()');
      Writeln(F,' ');
      Writeln(F,'InternalResultsResponse<Empresa> internalResultsResponse = getEmpresaDAC().updateEmpresa(empresaRequest)');
      Writeln(F,' ');
      Writeln(F,'if (!ValidationUtil.isNull(groupResponse))  ');
      Writeln(F,'{  ');
      Writeln(F,'internalResultsResponse.addMessages(groupResponse.getMessageInfoList())');
      Writeln(F,'} ');
      Writeln(F,' ');
      Writeln(F,'return internalResultsResponse');
      Writeln(F,'} ');
      Writeln(F,' ');
      Writeln(F,'@Override  ');
      Writeln(F,'public InternalResponse deleteEmpresa(EmpresaRequest empresaRequest)  ');
      Writeln(F,'{ ');
      Writeln(F,' ');
      Writeln(F,'InternalResultsResponse<Empresa> tagResponse =  ');
      Writeln(F,'(InternalResultsResponse<Empresa>)getEmpresaDAC().deleteEmpresa(empresaRequest)');
      Writeln(F,'InternalResponse response = new InternalResponse()');
      Writeln(F,' ');
      Writeln(F,'if (tagResponse.isInError())  ');
      Writeln(F,'{   ');
      Writeln(F,'return response');
      Writeln(F,'}  ');
      Writeln(F,' ');
      Writeln(F,'response = getEmpresaDAC().deleteEmpresa(empresaRequest)');
      Writeln(F,' ');
      Writeln(F,'if (tagResponse.isInError()) ');
      Writeln(F,'{      ');
      Writeln(F,'return response');
      Writeln(F,'}   ');
      Writeln(F,' ');
      Writeln(F,'Empresa empresa = tagResponse.getFirstResult()');
      Writeln(F,'empresaRequest.setEmpresa(empresa)');
      Writeln(F,' ');
      Writeln(F,'SearchParameter tagParameter =  ');
      Writeln(F,'new SearchParameter(PropertyEnum.EMPRESA_ID, String.valueOf(empresa.getCodemp()))');
      Writeln(F,'empresaRequest.getSearchLight().addSearchParameter(tagParameter)');
      Writeln(F,' ');
      Writeln(F,'InternalResultsResponse<Process> processResponse = ');
      Writeln(F,'insertProcess(empresaRequest, LCActionTypeEnum.DELETE_TAG, null)');
      Writeln(F,'empresaRequest.getSearchLight().getSearchParameters().remove(tagParameter)');
      Writeln(F,' ');
      Writeln(F,'if (processResponse.isInError())  ');
      Writeln(F,'{       ');
      Writeln(F,'response.setStatus(processResponse.getStatus())');
      Writeln(F,'response.addMessages(processResponse.getMessageInfoList())');
      Writeln(F,'}');
      Writeln(F,' ');
      Writeln(F,'return response');
      Writeln(F,'} ');
      Writeln(F,' ');
      Writeln(F,'@Override ');
      Writeln(F,'public InternalResultsResponse<Empresa> fetchAllEmpresa(InquiryEmpresaRequest inquiryempresaRequest) ');
      Writeln(F,'{   ');
      Writeln(F,'return getEmpresaDAC().fetchAllEmpresa(inquiryempresaRequest)');
      Writeln(F,'}  ');
      Writeln(F,' ');
      Writeln(F,'@Override  ');
      Writeln(F,'public InternalResultsResponse<Empresa> fetchEmpresaById(EmpresaRequest empresaRequest) ');
      Writeln(F,'{   ');
      Writeln(F,'return getEmpresaDAC().fetchEmpresaById(empresaRequest)');
      Writeln(F,'} ');
      Writeln(F,' ');
      Writeln(F,'public IEmpresaDAC getEmpresaDAC() ');
      Writeln(F,'{');
      Writeln(F,'return empresaDAC');
      Writeln(F,'} ');
      Writeln(F,' ');
      Writeln(F,'public void setEmpresaDAC(IEmpresaDAC empresaDAC) ');
      Writeln(F,'{ ');
      Writeln(F,'this.empresaDAC = empresaDAC');
      Writeln(F,'}  ');
      Writeln(F,' ');
      Writeln(F,'@Override  ');
      Writeln(F,'public InternalResultsResponse<Empresa> fetchAllEmpresaTypes(InquiryEmpresaRequest inquiryempresaRequest)  ');
      Writeln(F,'{ ');
      Writeln(F,'// TODO Auto-generated method stub  ');
      Writeln(F,'return null');
      Writeln(F,'}         ');
      Writeln(F,' ');
      Writeln(F,'private InternalResultsResponse<Process> insertProcess(EmpresaRequest empresaRequest,  ');
      Writeln(F,'LCActionTypeEnum lcActionType, ');
      Writeln(F,'String processDescription)   ');
      Writeln(F,'{ ');
      Writeln(F,'return insertProcess(empresaRequest, lcActionType, processDescription, null)');
      Writeln(F,'} ');
      Writeln(F,' ');
      Writeln(F,'/**   ');
      Writeln(F,'* Insert process. ');
      Writeln(F,'*   ');
      Writeln(F,'* @param tagRequest the tag request ');
      Writeln(F,'* @param lcActionType the lc action type   ');
      Writeln(F,'* @param processDescription the process description   ');
      Writeln(F,'* @return the internal results response  ');
      Writeln(F,'*/         ');
      Writeln(F,'private InternalResultsResponse<Process> insertProcess(EmpresaRequest tagRequest, LCActionTypeEnum lcActionType,  ');
      Writeln(F,'String processDescription, List<Light> deactivatedLights) ');
      Writeln(F,'{');
      Writeln(F,'Empresa empresa = tagRequest.getEmpresa()');
      Writeln(F,' ');
      Writeln(F,'List<LCActionParameter> actionParameters = new ArrayList<LCActionParameter>()');
      Writeln(F,'actionParameters.add(new LCActionParameter(PropertyEnum.TAG_ID, String.valueOf(empresa.getCodemp())))');
      Writeln(F,'actionParameters.add(new LCActionParameter(PropertyEnum.TAG_NAME, empresa.getCnpjemp()))');
      Writeln(F,' ');
      Writeln(F,'LCAction action = new LCAction(lcActionType)');
      Writeln(F,'action.setActionParameters(actionParameters)');
      Writeln(F,'action.setDescription("INSERT EMPRESA")');
      Writeln(F,'Process process = LCHelp.generateProcess(false, action, 0)');
      Writeln(F,'process.setIsProcessComplete(true)');
      Writeln(F,'process.setIsSubmitted(true)');
      Writeln(F,'process.setDescription("insert Empresa")');
      Writeln(F,'process.setRniCorrelationId("")');
      Writeln(F,' ');
      Writeln(F,' ');
      Writeln(F,'process.setEndTime(LCDateUtil.getNewDateUTC())');
      Writeln(F,' ');
      Writeln(F,'if (!ValidationUtil.isNullOrEmpty(processDescription))  ');
      Writeln(F,'{ ');
      Writeln(F,'process.setDescription(processDescription)');
      Writeln(F,'} ');
      Writeln(F,' ');
      Writeln(F,'ProcessRequest processRequest = createProcessRequest(tagRequest, process)');
      Writeln(F,'processRequest.setProcessItemFailureList( ');
      Writeln(F,'createProcessItemWithFailure(  ');
      Writeln(F,'	deactivatedLights,     ');
      Writeln(F,'	ProcessItemStatusEnum.MLCFAILURE,  ');
      Writeln(F,'	ProcessStatusReasonEnum.LIGHT_DEACTIVATED))');
      Writeln(F,' ');
      Writeln(F,'return getProcessBCL().insertProcess(processRequest)');
      Writeln(F,'} ');
      Writeln(F,' ');
      Writeln(F,'@Override  ');
      Writeln(F,'public InternalResultsResponse<Empresa> fetchAllEmpresaFilial(EmpresaRequest empresaRequest) ');
      Writeln(F,'{  ');
      Writeln(F,'// TODO Auto-generated method stub  ');
      Writeln(F,'return null');
      Writeln(F,'} ');
      Writeln(F,'}  ');
      Writeln(F,' ');
      Closefile(F);
end;


function TForm1.criarCodeIClasseBCL(Txt:String):String;
begin
      AssignFile(F,'c:\'+PrimeiraMaiscula(Edit1.Text)+'BCL.java');
      Writeln(F,'package com.sensus.mlc.empresa.bcl;');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'import com.sensus.common.model.response.InternalResponse; ');
      Writeln(F,'import com.sensus.common.model.response.InternalResultsResponse;');
      Writeln(F,'import com.sensus.mlc.empresa.model.Empresa; ');
      Writeln(F,'import com.sensus.mlc.empresa.model.request.EmpresaRequest; ');
      Writeln(F,'import com.sensus.mlc.empresa.model.request.InquiryEmpresaRequest; ');
      Writeln(F,' ');
      Writeln(F,'// TODO: Auto-generated Javadoc ');
      Writeln(F,'/**');
      Writeln(F,' * The Interface IActionBCL.');
      Writeln(F,' * ');
      Writeln(F,' * @author - QAT Brazil. ');
      Writeln(F,' * ');
      Writeln(F,' */ ');
      Writeln(F,'public interface IEmpresaBCL ');
      Writeln(F,'{   ');
      Writeln(F,'    ');
      Writeln(F,'	/**  ');
      Writeln(F,'	 * Insert empresa. ');
      Writeln(F,'	 * ');
      Writeln(F,'	 * @param empresaRequest the empresa request  ');
      Writeln(F,'	 * @return the empresa response  ');
      Writeln(F,'	 */ ');
      Writeln(F,'	public InternalResultsResponse<Empresa> insertEmpresa(EmpresaRequest empresaRequest);');
      Writeln(F,'  ');
      Writeln(F,'	/** ');
      Writeln(F,'	 * Update empresa. ');
      Writeln(F,'	 *  ');
      Writeln(F,'	 * @param empresaRequest the empresa request ');
      Writeln(F,'	 * @return the empresa response ');
      Writeln(F,'	 */  ');
      Writeln(F,'	public InternalResultsResponse<Empresa> updateEmpresa(EmpresaRequest empresaRequest); ');
      Writeln(F,'   ');
      Writeln(F,'	/** ');
      Writeln(F,'	 * Delete empresa. ');
      Writeln(F,'	 *   ');
      Writeln(F,'	 * @param empresaRequest the empresa request ');
      Writeln(F,'	 * @return the empresa response  ');
      Writeln(F,'	 */ ');
      Writeln(F,'	public InternalResponse deleteEmpresa(EmpresaRequest empresaRequest); ');
      Writeln(F,'  ');
      Writeln(F,'	/** ');
      Writeln(F,'	 * Fetch all empresa.');
      Writeln(F,'	 *   ');
      Writeln(F,'	 * @param inquiryempresaRequest the inquiryempresa request ');
      Writeln(F,'	 * @return the inquiry empresa response ');
      Writeln(F,'	 */  ');
      Writeln(F,'	public InternalResultsResponse<Empresa> fetchAllEmpresa(InquiryEmpresaRequest inquiryempresaRequest);');
      Writeln(F,'  ');
      Writeln(F,'	/** ');
      Writeln(F,'	 * Fetch empresa by id. ');
      Writeln(F,'	 * ');
      Writeln(F,'	 * @param inquiryempresaRequest the inquiryempresa request');
      Writeln(F,'	 * @return the internal results response   ');
      Writeln(F,'	 */ ');
      Writeln(F,'	public InternalResultsResponse<Empresa> fetchEmpresaById(EmpresaRequest empresaRequest); ');
      Writeln(F,' ');
      Writeln(F,'	/** ');
      Writeln(F,'	 * Fetch all empresa types. ');
      Writeln(F,'	 * ');
      Writeln(F,'	 * @param request the request ');
      Writeln(F,'	 * @return the empresa response ');
      Writeln(F,'	 */ ');
      Writeln(F,'	public InternalResultsResponse<Empresa> fetchAllEmpresaTypes(InquiryEmpresaRequest inquiryempresaRequest);  ');
      Writeln(F,'  ');
      Writeln(F,'	/** ');
      Writeln(F,'	 * Fetch all empresa filial. ');
      Writeln(F,'	 *  ');
      Writeln(F,'	 * @param request the request ');
      Writeln(F,'	 * @return the empresa response ');
      Writeln(F,'	 */ ');
      Writeln(F,'	public InternalResultsResponse<Empresa> fetchAllEmpresaFilial(EmpresaRequest empresaRequest);');
      Writeln(F,' ');
      Writeln(F,'} ');
      Closefile(F);
end;
function TForm1.criarCodeClasseBCFImpl(Txt:String):String;
begin
      AssignFile(F,'c:\I'+PrimeiraMaiscula(Edit1.Text)+'BCF.java');
      Writeln(F,'');
      Writeln(F,'package com.sensus.mlc.'+Edit1.Text+'.bcf.impl;');
      Writeln(F,'');
      Writeln(F,'import org.slf4j.Logger;');
      Writeln(F,'import org.slf4j.LoggerFactory;');
      Writeln(F,'');
      Writeln(F,'import com.sensus.common.model.request.Request;');
      Writeln(F,'import com.sensus.common.model.response.InternalResponse;');
      Writeln(F,'import com.sensus.common.model.response.InternalResultsResponse;');
      Writeln(F,'import com.sensus.common.util.SensusInterfaceUtil;');
      Writeln(F,'import com.sensus.mlc.base.model.MLCPersistanceActionEnum;');
      Writeln(F,'import com.sensus.mlc.base.util.LCHelp;');
      Writeln(F,'import com.sensus.mlc.empresa.bcf.IEmpresaBCF;');
      Writeln(F,'import com.sensus.mlc.empresa.bcl.IEmpresaBCL;');
      Writeln(F,'import com.sensus.mlc.empresa.model.Empresa;');
      Writeln(F,'import com.sensus.mlc.empresa.model.request.EmpresaRequest;');
      Writeln(F,'import com.sensus.mlc.empresa.model.request.InquiryEmpresaRequest;');
      Writeln(F,'import com.sensus.mlc.empresa.model.response.EmpresaResponse;');
      Writeln(F,'import com.sensus.mlc.empresa.model.response.InquiryEmpresaResponse;');
      Writeln(F,'import com.sensus.mlc.process.model.response.ProcessResponse;');
      Writeln(F,'import com.sensus.mlc.tag.bcf.impl.TagBCFImpl;');
      Writeln(F,'');
      Writeln(F,'public class EmpresaBCFImpl implements IEmpresaBCF');
      Writeln(F,'{');
      Writeln(F,'');
      Writeln(F,'	/** The Constant NAME_LENGTH. */');
      Writeln(F,'	private static final Integer NAME_LENGTH = 255;');
      Writeln(F,' ');
      Writeln(F,'	/** The Constant SENSUS_EPM_ACTIONVALIDATOR_NAME_INVALID. */ ');
      Writeln(F,'	private static final String SENSUS_EPM_ACTIONVALIDATOR_NAME_INVALID = ');
      Writeln(F,'			"sensus.epm.actionvalidator.name.invalid"; ');
      Writeln(F,'');
      Writeln(F,'	/** The Constant DEFAULT_GROUP_BCF_EXCEPTION_MSG. */ ');
      Writeln(F,'	private static final String DEFAULT_EMPRESA_BCF_EXCEPTION_MSG = "sensus.mlc.groupbcfimpl.defaultexception"; ');
      Writeln(F,' ');
      Writeln(F,'	/** The Constant DEFAULT_GROUP_BCL_EXCEPTION_MSG. */ ');
      Writeln(F,'	private static final String DEFAULT_EMPRESA_BCL_EXCEPTION_MSG = "sensus.mlc.groupbclimpl.defaultexception";');
      Writeln(F,' ');
      Writeln(F,'	/** The Constant LOG. */');
      Writeln(F,'	private static final Logger LOG = LoggerFactory.getLogger(TagBCFImpl.class); ');
      Writeln(F,' ');
      Writeln(F,'	private IEmpresaBCL empresaBCL; // injected by Spring through setter');
      Writeln(F,' ');
      Writeln(F,'	@Override ');
      Writeln(F,'	public EmpresaResponse insertEmpresa(EmpresaRequest empresaRequest)');
      Writeln(F,'	{');
      Writeln(F,'		EmpresaResponse response = new EmpresaResponse();');
      Writeln(F,' ');
      Writeln(F,'		try ');
      Writeln(F,'		{ ');
      Writeln(F,'     ');
      Writeln(F,'			if (LCHelp.checkValidation(response, empresaRequest, new Object[] {MLCPersistanceActionEnum.INSERT}))');
      Writeln(F,'			{');
      Writeln(F,'				InternalResultsResponse<Empresa> internalResponse = getEmpresaBCL().insertEmpresa(empresaRequest); ');
      Writeln(F,'				response.setEmpresa(internalResponse.getResultsList()); ');
      Writeln(F,'				LCHelp.treatReturnFromBCL(response, internalResponse, DEFAULT_EMPRESA_BCF_EXCEPTION_MSG); ');
      Writeln(F,'			}');
      Writeln(F,'		} ');
      Writeln(F,'		catch (Exception ex) ');
      Writeln(F,'		{ ');
      Writeln(F,'			SensusInterfaceUtil.handleException(LOG, response, ex, DEFAULT_EMPRESA_BCF_EXCEPTION_MSG);');
      Writeln(F,'		}');
      Writeln(F,'');
      Writeln(F,'		return response;');
      Writeln(F,'	}');
      Writeln(F,'');
      Writeln(F,'	@Override');
      Writeln(F,'	public EmpresaResponse updateEmpresa(EmpresaRequest empresaRequest)');
      Writeln(F,'	{');
      Writeln(F,'		EmpresaResponse response = new EmpresaResponse();');
      Writeln(F,'		try ');
      Writeln(F,'		{ ');
      Writeln(F,'			if (LCHelp.checkValidation(response, empresaRequest, MLCPersistanceActionEnum.UPDATE)) ');
      Writeln(F,'			{  ');
      Writeln(F,'				InternalResultsResponse<Empresa> internalResponse = getEmpresaBCL().updateEmpresa(empresaRequest);');
      Writeln(F,'				response.setEmpresa(internalResponse.getResultsList());');
      Writeln(F,'				LCHelp.treatReturnFromBCL(response, internalResponse, DEFAULT_EMPRESA_BCL_EXCEPTION_MSG);');
      Writeln(F,'			}');
      Writeln(F,'		} ');
      Writeln(F,'		catch (Exception ex) ');
      Writeln(F,'		{ ');
      Writeln(F,'			SensusInterfaceUtil.handleException(LOG, response, ex, DEFAULT_EMPRESA_BCF_EXCEPTION_MSG);');
      Writeln(F,'		} ');
      Writeln(F,'		return response;  ');
      Writeln(F,'	} ');
      Writeln(F,'   ');
      Writeln(F,'	@Override  ');
      Writeln(F,'	public EmpresaResponse deleteEmpresa(EmpresaRequest empresaRequest) ');
      Writeln(F,'	{  ');
      Writeln(F,'		EmpresaResponse response = new EmpresaResponse();');
      Writeln(F,'		try  ');
      Writeln(F,'		{  ');
      Writeln(F,'			if (LCHelp.checkValidation(response, empresaRequest, MLCPersistanceActionEnum.DELETE)) ');
      Writeln(F,'			{  ');
      Writeln(F,'				InternalResponse internalResponse = getEmpresaBCL().deleteEmpresa(empresaRequest); ');
      Writeln(F,'				LCHelp.treatReturnFromBCL(response, internalResponse, DEFAULT_EMPRESA_BCF_EXCEPTION_MSG); ');
      Writeln(F,'			}  ');
      Writeln(F,'		}  ');
      Writeln(F,'		catch (Exception ex)');
      Writeln(F,'		{ ');
      Writeln(F,'			SensusInterfaceUtil.handleException(LOG, response, ex, DEFAULT_EMPRESA_BCF_EXCEPTION_MSG); ');
      Writeln(F,'		} ');
      Writeln(F,'		return response; ');
      Writeln(F,'	} ');
      Writeln(F,'  ');
      Writeln(F,'	@Override ');
      Writeln(F,'	public InquiryEmpresaResponse fetchAllEmpresa(InquiryEmpresaRequest inquiryempresaRequest) ');
      Writeln(F,'	{ ');
      Writeln(F,'		InquiryEmpresaResponse response = new InquiryEmpresaResponse(); ');
      Writeln(F,'		try ');
      Writeln(F,'		{ ');
      Writeln(F,'    ');
      Writeln(F,'				InternalResultsResponse<Empresa> internalResponse =  ');
      Writeln(F,'						getEmpresaBCL().fetchAllEmpresa(inquiryempresaRequest); ');
      Writeln(F,'				response.setEmpresa(internalResponse.getResultsList());');
      Writeln(F,'				response.setResultsSetInfo(internalResponse.getResultsSetInfo());');
      Writeln(F,'				LCHelp.treatReturnFromBCL(response, internalResponse, DEFAULT_EMPRESA_BCF_EXCEPTION_MSG); ');
      Writeln(F,'   ');
      Writeln(F,'		}');
      Writeln(F,'		catch (Exception ex)');
      Writeln(F,'		{ ');
      Writeln(F,'			SensusInterfaceUtil.handleException(LOG, response, ex, DEFAULT_EMPRESA_BCF_EXCEPTION_MSG); ');
      Writeln(F,'		}  ');
      Writeln(F,'		return response;');
      Writeln(F,'	} ');
      Writeln(F,'   ');
      Writeln(F,'	@Override  ');
      Writeln(F,'	public EmpresaResponse fetchEmpresaById(EmpresaRequest empresaRequest) ');
      Writeln(F,'	{ ');
      Writeln(F,'		EmpresaResponse response = new EmpresaResponse(); ');
      Writeln(F,'		try ');
      Writeln(F,'		{  ');
      Writeln(F,'			if (LCHelp.checkValidation(response, empresaRequest, MLCPersistanceActionEnum.FETCH_BY_ID)) ');
      Writeln(F,'			{ ');
      Writeln(F,'				InternalResultsResponse<Empresa> internalResponse = getEmpresaBCL().fetchEmpresaById(empresaRequest); ');
      Writeln(F,'				response.setEmpresa(internalResponse.getResultsList());');
      Writeln(F,'				LCHelp.treatReturnFromBCL(response, internalResponse, DEFAULT_EMPRESA_BCF_EXCEPTION_MSG); ');
      Writeln(F,'			} ');
      Writeln(F,'		}  ');
      Writeln(F,'		catch (Exception ex)  ');
      Writeln(F,'		{      ');
      Writeln(F,'			SensusInterfaceUtil.handleException(LOG, response, ex, DEFAULT_EMPRESA_BCF_EXCEPTION_MSG);  ');
      Writeln(F,'		}');
      Writeln(F,'		return response;  ');
      Writeln(F,'	}');
      Writeln(F,'  ');
      Writeln(F,'	@Override ');
      Writeln(F,'	public EmpresaResponse fetchAllEmpresaFilial(EmpresaRequest empresaRequest) { ');
      Writeln(F,'		EmpresaResponse response = new EmpresaResponse(); ');
      Writeln(F,'		try ');
      Writeln(F,'		{    ');
      Writeln(F,'			if (LCHelp.checkValidation(response, inquiryEmpresaRequest, MLCPersistanceActionEnum.FETCH)) ');
      Writeln(F,'			{ ');
      Writeln(F,'				InternalResultsResponse<Empresa> internalResponse =  ');
      Writeln(F,'						getEmpresaBCL().fetchAllEmpresaFilial(empresaRequest);  ');
      Writeln(F,'				response.setEmpresa(internalResponse.getResultsList());   ');
      Writeln(F,'				LCHelp.treatReturnFromBCL(response, internalResponse, DEFAULT_EMPRESA_BCF_EXCEPTION_MSG); ');
      Writeln(F,'			}  ');
      Writeln(F,'		} ');
      Writeln(F,'		catch (Exception ex) ');
      Writeln(F,'		{  ');
      Writeln(F,'			SensusInterfaceUtil.handleException(LOG, response, ex, DEFAULT_EMPRESA_BCF_EXCEPTION_MSG); ');
      Writeln(F,'		} ');
      Writeln(F,'		return response; ');
      Writeln(F,'	} ');
      Writeln(F,'   ');
      Writeln(F,'   ');
      Writeln(F,'	public IEmpresaBCL getEmpresaBCL() ');
      Writeln(F,'	{       ');
      Writeln(F,'		return empresaBCL; ');
      Writeln(F,'	}  ');
      Writeln(F,'    ');
      Writeln(F,'	public void setEmpresaBCL(IEmpresaBCL empresaBCL) ');
      Writeln(F,'	{ ');
      Writeln(F,'		this.empresaBCL = empresaBCL; ');
      Writeln(F,'	} ');
      Writeln(F,'}  ');
      Closefile(F);
end;

function TForm1.criarCodeIClasseBCF(Txt:String):String;
begin
      AssignFile(F,'c:\I'+PrimeiraMaiscula(Edit1.Text)+'BCF.java');
      Writeln(F,'package com.sensus.mlc.'+Edit1.Text+'.bcf;');
      Writeln(F,'');
      Writeln(F,'import com.sensus.common.model.request.Request;');
      Writeln(F,'import com.sensus.mlc.'+Edit1.Text+'.model.request.'+PrimeiraMaiscula(Edit1.Text)+'Request;');
      Writeln(F,'import com.sensus.mlc.'+Edit1.Text+'.model.request.Inquiry'+PrimeiraMaiscula(Edit1.Text)+'Request;');
      Writeln(F,'import com.sensus.mlc.'+Edit1.Text+'.model.response.'+PrimeiraMaiscula(Edit1.Text)+'Response;');
      Writeln(F,'import com.sensus.mlc.'+Edit1.Text+'.model.response.Inquiry'+PrimeiraMaiscula(Edit1.Text)+'Response;');
      Writeln(F,'import com.sensus.mlc.process.model.response.ProcessResponse;');
      Writeln(F,'');
      Writeln(F,'');
      Writeln(F,'/** ');
      Writeln(F,' * The Interface I'+PrimeiraMaiscula(Edit1.Text)+'BCF.');
      Writeln(F,' *');
      Writeln(F,' * @author Washington.Costa');
      Writeln(F,' */');
      Writeln(F,'public interface I'+PrimeiraMaiscula(Edit1.Text)+'BCF ');
      Writeln(F,'{');
      Writeln(F,'');
      Writeln(F,'	/** ');
      Writeln(F,'	 * Insert '+Edit1.Text+'.');
      Writeln(F,'	 *');
      Writeln(F,'	 * @param '+Edit1.Text+'Request the '+Edit1.Text+' request');
      Writeln(F,'	 * @return the '+Edit1.Text+' response ');
      Writeln(F,'	 */');
      Writeln(F,'	public '+PrimeiraMaiscula(Edit1.Text)+'Response insert'+PrimeiraMaiscula(Edit1.Text)+'('+PrimeiraMaiscula(Edit1.Text)+'Request '+Edit1.Text+'Request);');
      Writeln(F,'  ');
      Writeln(F,'	/**');
      Writeln(F,'	 * Update '+Edit1.Text+'.');
      Writeln(F,'	 *');
      Writeln(F,'	 * @param '+Edit1.Text+'Request the '+Edit1.Text+' request');
      Writeln(F,'	 * @return the '+Edit1.Text+' response');
      Writeln(F,'	 */');
      Writeln(F,'	public '+PrimeiraMaiscula(Edit1.Text)+'Response update'+PrimeiraMaiscula(Edit1.Text)+'('+PrimeiraMaiscula(Edit1.Text)+'Request '+Edit1.Text+'Request);');
      Writeln(F,'  ');
      Writeln(F,'	/**  ');
      Writeln(F,'	 * Delete '+Edit1.Text+'.  ');
      Writeln(F,'	 *     ');
      Writeln(F,'	 * @param '+Edit1.Text+'Request the '+Edit1.Text+' request ');
      Writeln(F,'	 * @return the '+Edit1.Text+' response');
      Writeln(F,'	 */');
      Writeln(F,'	public '+PrimeiraMaiscula(Edit1.Text)+'Response delete'+PrimeiraMaiscula(Edit1.Text)+'('+PrimeiraMaiscula(Edit1.Text)+'Request '+Edit1.Text+'Request); ');
      Writeln(F,'   ');
      Writeln(F,'	/**  ');
      Writeln(F,'	 * Fetch all '+Edit1.Text+'. ');
      Writeln(F,'	 *  ');
      Writeln(F,'	 * @param inquiry'+PrimeiraMaiscula(Edit1.Text)+'Request the inquiry'+PrimeiraMaiscula(Edit1.Text)+' request   ');
      Writeln(F,'	 * @return the inquiry '+Edit1.Text+' response ');
      Writeln(F,'	 */ ');
      Writeln(F,'	public Inquiry'+PrimeiraMaiscula(Edit1.Text)+'Response fetchAll'+PrimeiraMaiscula(Edit1.Text)+'(Inquiry'+PrimeiraMaiscula(Edit1.Text)+'Request inquiry'+PrimeiraMaiscula(Edit1.Text)+'Request); ');
      Writeln(F,'   ');
      Writeln(F,'	/** ');
      Writeln(F,'	 * Fetch '+Edit1.Text+' by id. ');
      Writeln(F,'	 *   ');
      Writeln(F,'	 * @param '+PrimeiraMaiscula(Edit1.Text)+'Request the '+Edit1.Text+' request ');
      Writeln(F,'	 * @return the '+Edit1.Text+' response  ');
      Writeln(F,'	 */ ');
      Writeln(F,'	public '+PrimeiraMaiscula(Edit1.Text)+'Response fetch'+PrimeiraMaiscula(Edit1.Text)+'ById('+PrimeiraMaiscula(Edit1.Text)+'Request '+Edit1.Text+'Request); ');
      Writeln(F,' ');
      Writeln(F,'} ');
      Closefile(F);
end;
function TForm1.criarCodeResponse(Txt:String):String;
begin
       AssignFile(F,'c:\'+PrimeiraMaiscula(Edit1.Text)+'response.java');
       Rewrite(F); //abre o arquivo para escrita
       Writeln(F,'package com.sensus.mlc.'+Edit1.Text+'.model.response;');
       Writeln(F,'import java.util.List;');
       Writeln(F,'import com.sensus.common.model.response.Response;');
       Writeln(F,'import com.sensus.mlc.'+Edit1.Text+'.model.'+PrimeiraMaiscula(Edit1.Text)+';');
       Writeln(F,'');
       Writeln(F,'');
       Writeln(F,'public class '+PrimeiraMaiscula(Edit1.Text)+'Response extends Response');
       Writeln(F,'');
       Writeln(F,'    ');
       Writeln(F,'    private Integer parentRetry;');
       Writeln(F,'    ');
       Writeln(F,'    private List<'+PrimeiraMaiscula(Edit1.Text)+'> '+Edit1.Text+';');
       Writeln(F,'}');
       Closefile(F);
end;
function TForm1.criarCodeRequest(Txt:String):String;
begin
       AssignFile(F,'c:\'+PrimeiraMaiscula(Edit1.Text)+'request.java');
       Rewrite(F); //abre o arquivo para escrita
       Writeln(F,'package com.sensus.mlc.'+Edit1.Text+'.model.request;');
       Writeln(F,'import java.util.List;');
       Writeln(F,'import com.sensus.mlc.base.model.request.LightSelectionRequest;');
       Writeln(F,'import com.sensus.mlc.'+Edit1.Text+'.model.'+PrimeiraMaiscula(Edit1.Text)+';');
       Writeln(F,'');
       Writeln(F,'');
       Writeln(F,'public class '+PrimeiraMaiscula(Edit1.Text)+'Request extends LightSelectionRequest');
       Writeln(F,'');
       Writeln(F,'    ');
       Writeln(F,'    private Integer parentRetry;');
       Writeln(F,'    ');
       Writeln(F,'    private '+PrimeiraMaiscula(Edit1.Text)+'  '+Edit1.Text+';');
       Writeln(F,'}');
       Closefile(F);
end;

Function TForm1.MostrarMemo(Memo: TMemo) : String;
 var   linha: string;
begin
      CloseFile(F);
      Reset(F);   // [ 3 ] Abre o arquivo texto para leitura
      {$I+}         // ativa a diretiva de Input

      if (IOResult <> 0) then
          Memo.Lines.Add('Erro na abertura do arquivo !!!')
      else begin
         while (not eof(F)) do
         begin
           readln(F, linha); // [ 6 ] Lê uma linha do arquivo
           Memo.Lines.Add(linha);
         end;

         CloseFile(F); // [ 8 ] Fecha o arquivo texto aberto
       end;
end;

Function TForm1.PrimeiraMaiscula(Texto: String) : String;
begin
      Texto := lowerCase(Texto);
      If Length(Trim(Texto))>0 Then//verifica se o edit está vazio ou somente com "espaços" em branco
      Texto:= UPPERCASE(Copy(Texto, 1, 1))+ LOWERCASE(Copy(Texto, 2, Length(Texto)));
      Result := Texto;
end;
function TForm1.criarCodeInquiryRequest(Txt:String):String;
begin

       AssignFile(F,'c:\Inquiry'+PrimeiraMaiscula(Edit1.Text)+'request.java');
       Rewrite(F); //abre o arquivo para escrita
       Writeln(F,'package com.sensus.mlc.'+Edit1.Text+'.model.request;');
       Writeln(F,'import java.util.List;');
       Writeln(F,'import com.sensus.mlc.base.model.BaseSearch;');
       Writeln(F,'import com.sensus.mlc.base.model.request.InquiryPaginationRequest;');
       Writeln(F,'import com.sensus.mlc.'+Edit1.Text+'.model.'+PrimeiraMaiscula(Edit1.Text)+';');
       Writeln(F,'');
       Writeln(F,'');
       Writeln(F,'public class Inquiry'+PrimeiraMaiscula(Edit1.Text)+'Request extends InquiryPaginationRequest');
       Writeln(F,'');
       Writeln(F,'    private BaseSearch baseSearch;');
       Writeln(F,'    ');
       Writeln(F,'    private String fileName;');
       Writeln(F,'    ');
       Writeln(F,'    Integer processId;');
       Writeln(F,'    ');
       Writeln(F,'    private List<'+PrimeiraMaiscula(Edit1.Text)+'> '+Edit1.Text+';');
       Writeln(F,'}');
       Closefile(F);
end;



function TForm1.criarCodeInquiryResponse(Txt:String):String;
begin
       AssignFile(F,'c:\Inquiry'+PrimeiraMaiscula(Edit1.Text)+'Response.java');
       Rewrite(F); //abre o arquivo para escrita
       Writeln(F,'import java.util.List;');
       Writeln(F,'import com.sensus.common.model.response.InquiryResponse');
       Writeln(F,'');
       Writeln(F,'');
       Writeln(F,'public class Inquiry'+PrimeiraMaiscula(Edit1.Text)+'Response extends InquiryResponse');
       Writeln(F,'');
       Writeln(F,'    private List<'+PrimeiraMaiscula(Edit1.Text)+'> '+Edit1.Text+';');
       Writeln(F,'');
       Writeln(F,'');
	     Writeln(F,'    public List<'+PrimeiraMaiscula(Edit1.Text)+'> get'+PrimeiraMaiscula(Edit1.Text)+'() {');
       Writeln(F,'      return '+Edit1.Text+';');
       Writeln(F,'    }');
       Writeln(F,'');
       Writeln(F,'');
       Writeln(F,'    public void set'+PrimeiraMaiscula(Edit1.Text)+'(List<'+PrimeiraMaiscula(Edit1.Text)+'> '+Edit1.Text+') {');
       Writeln(F,'        this.'+Edit1.Text+' = '+Edit1.Text+';');
       Writeln(F,     '}');
       Writeln(F,'');
       Writeln(F,'');
       Writeln(F,'');
       Writeln(F,'    public String toString() {');
//       Writeln(F,'                                                                                                                                                       ');
       Writeln(F,'    return "InquiryTelaResponse ['+Edit1.Text+'=" + '+Edit1.Text);
       Writeln(F,'      + ", get'+PrimeiraMaiscula(Edit1.Text)+'()=" + get'+PrimeiraMaiscula(Edit1.Text)+'()');
       Writeln(F,'    + "]";');
       Writeln(F,'');
       Writeln(F,'');
       Writeln(F,'}');
       Closefile(F);
end;

function TForm1.verificadorCode(Txt:String):String;
begin
      if Pos(UpperCase('Char'),UpperCase(Txt)) <> 0  then
      begin
          result := 'String'
      end
      else if Pos(UpperCase('INTEGER'),UpperCase(Txt)) <> 0  then
      begin
          result := 'Integer'
      end
      else if Pos(UpperCase('SMALLINT'),UpperCase(Txt)) <> 0  then
      begin
            result := 'String'
      end
      else if Pos(UpperCase('NUMERIC'),UpperCase(Txt)) <> 0  then
      begin
            result := 'Double'
      end
      else if Pos(UpperCase('TIME'),UpperCase(Txt)) <> 0  then
      begin
            result := 'Date'
      end
      else
      begin
           result := Txt
      end

end;
Function TForm1.Explode(Texto, Separador : String) : String;
var
    strItem       : String;
    ListaAuxUTILS : TStrings;
    NumCaracteres,
    TamanhoSeparador,
    I : Integer;
Begin
    ListaAuxUTILS    := TStringList.Create;
    strItem          := '';
    NumCaracteres    := Length(Texto);
    TamanhoSeparador := Length(Separador);
    I                := 1;
    While I <= NumCaracteres Do
      Begin
        If (Copy(Texto,I,TamanhoSeparador) = Separador) or (I = NumCaracteres) Then
          Begin
            if (I = NumCaracteres) then strItem := strItem + Texto[I];
            ListaAuxUTILS.Add(trim(strItem));
            strItem := '';
            I := I + (TamanhoSeparador-1);
          end
        Else
            strItem := strItem + Texto[I];

        I := I + 1;
      End;
    Explode := ListaAuxUTILS.Text;
end;

function TForm1.escreverCode(Txt:String):String;
var
  strLinha: String;
  Parte : TStringList;
begin
  strLinha := 'ab|c|d e|f';

  Parte := TStringList.Create;
  try
  Parte.Clear;
  ExtractStrings([' '],[], PChar(Txt), Parte);
  if('CREATE' <> Parte[0])  then
  result := verificadorCode(Parte[1])+' '+ Parte[0] +';';
  finally
    Parte.Free;
  end; end;
procedure TForm1.gerarModelo(Txt:String);
var linha: string;
BEGIN
     Closefile(F);
     AssignFile(F,'c:\'+Edit1.Text+'.java');
     Rewrite(F); //abre o arquivo para escrita
     Writeln(F,'public class '+Txt+' extends SensusModel'); //escreve no arquivo e desce uma linha
     Writeln(F,'{');
     AssignFile(arq, BrvEdit1.Text);

     Reset(arq);   // [ 3 ] Abre o arquivo texto para leitura
     {$I+}
     while (not eof(arq)) do
     begin
           readln(arq, linha); // [ 6 ] Lê uma linha do arquivo
           Writeln(F,'    '+escreverCode(linha));
      end;

      CloseFile(arq); // [ 8 ] Fecha o arquivo texto aberto


      Writeln(F,'}');
      Closefile(F); //fecha o handle de arquivo

END;

procedure TForm1.BtnPesquisaClick(Sender: TObject);
begin
     if CheckBox1.Checked = true then
     begin
           criarCodeIClasseBCF(Edit1.Text);
           MostrarMemo(Memo8);
     end;
     if CheckBox2.Checked = true then
     begin
           criarCodeClasseBCFImpl(Edit1.Text);
           MostrarMemo(Memo8);
     end;
     if CheckBox3.Checked = true then
     begin
           criarCodeIClasseBCL(Edit1.Text);
           MostrarMemo(Memo8);
     end;
     if CheckBox9.Checked = true then
     begin
           gerarModelo(Edit1.Text);
           MostrarMemo(Memo3);
     end;
     if CheckBox10.Checked = true then
     begin
           criarCodeRequest(Edit1.Text);
           MostrarMemo(Memo6);
     end;
     if CheckBox11.Checked = true then
     begin
           criarCodeResponse(Edit1.Text);
           MostrarMemo(Memo7);
     end;
     if CheckBox18.Checked = true then
     begin
           criarCodeInquiryResponse(Edit1.Text);
           MostrarMemo(Memo4);
     end;
     if CheckBox19.Checked = true then
     begin
           criarCodeInquiryRequest(Edit1.Text);
           MostrarMemo(Memo5);
     end;
end;

procedure TForm1.SpeedButton1Click(Sender: TObject);
var   arq: TextFile; { declarando a variável "arq" do tipo arquivo texto }
    linha: string;
begin
  Memo1.Clear;

  AssignFile(arq, BrvEdit1.Text);

  Reset(arq);   // [ 3 ] Abre o arquivo texto para leitura
  {$I+}         // ativa a diretiva de Input

  if (IOResult <> 0) // verifica o resultado da operação de abertura
     then Memo1.Lines.Add('Erro na abertura do arquivo !!!')
  else begin
         while (not eof(arq)) do
         begin
           readln(arq, linha); // [ 6 ] Lê uma linha do arquivo
           Memo1.Lines.Add(linha);
         end;

         CloseFile(arq); // [ 8 ] Fecha o arquivo texto aberto
       end;
end;
end.
