INSERT INTO CSOSN (CODIGO, DESCRICAO)
           VALUES ('101', '101 - TRIBUTADA COM PERMISSAO DE CREDITO');
INSERT INTO CSOSN (CODIGO, DESCRICAO)
           VALUES ('102', '102 - TRIBUTADA SEM PERMISSAO DE CREDITO');
INSERT INTO CSOSN (CODIGO, DESCRICAO)
           VALUES ('103', '103 - ISENCAO DO ICMS PARA FAIXA DE RECEITA BRUTA');
INSERT INTO CSOSN (CODIGO, DESCRICAO)
           VALUES ('201', '201 - TRIBUTADA COM PERMISSAO DE CREDITO E COM COBRANCA DO ICMS POR ST');
INSERT INTO CSOSN (CODIGO, DESCRICAO)
           VALUES ('202', '202 - TRIBUTADA SEM PERMISSAO DE CREDITO E COM COBRANCA DO ICMS POR ST');
INSERT INTO CSOSN (CODIGO, DESCRICAO)
           VALUES ('203', '203 - ISENCAO DO ICMS PARA FAIXA DE RECEITA BRUTA E COM COBRANCA DO ICMS POR ST');
INSERT INTO CSOSN (CODIGO, DESCRICAO)
           VALUES ('300', '300 - IMUNE');
INSERT INTO CSOSN (CODIGO, DESCRICAO)
           VALUES ('400', '400 - NÃO TRIBUTADA');
INSERT INTO CSOSN (CODIGO, DESCRICAO)
           VALUES ('500', '500 - ICMS COBRADO ANTERIORMENTE POR ST OU POR ANTECIPACAO');
INSERT INTO CSOSN (CODIGO, DESCRICAO)
           VALUES ('900', '900 - OUTROS');

COMMIT WORK;
